-- Cambridge YLE Vocabulary - Full seed data for Qarint Junior
-- Source: Cambridge Young Learners English (Pre A1 Starters, A1 Movers, A2 Flyers)
-- 304 words total

DELETE FROM vocabulary_words;

INSERT INTO vocabulary_words (word, translation, openmoji_hex, category, level, is_cultural_value) VALUES
('animal', 'hayvan', '1F43E', 'animals', 'pre_a1_starters', false),
('bear', 'ayı', '1F43B', 'animals', 'pre_a1_starters', false),
('bee', 'arı', '1F41D', 'animals', 'pre_a1_starters', false),
('bird', 'kuş', '1F426', 'animals', 'pre_a1_starters', false),
('cat', 'kedi', '1F431', 'animals', 'pre_a1_starters', false),
('chicken', 'tavuk', '1F414', 'animals', 'pre_a1_starters', false),
('cow', 'inek', '1F404', 'animals', 'pre_a1_starters', false),
('crocodile', 'timsah', '1F40A', 'animals', 'pre_a1_starters', false),
('dog', 'köpek', '1F436', 'animals', 'pre_a1_starters', false),
('dolphin', 'yunus', '1F42C', 'animals', 'a1_movers', false),
('donkey', 'eşek', '1F434', 'animals', 'a1_movers', false),
('duck', 'ördek', '1F986', 'animals', 'pre_a1_starters', false),
('elephant', 'fil', '1F418', 'animals', 'pre_a1_starters', false),
('fish', 'balık', '1F41F', 'animals', 'pre_a1_starters', false),
('fly', 'sinek', '1FAB0', 'animals', 'a1_movers', false),
('frog', 'kurbağa', '1F438', 'animals', 'pre_a1_starters', false),
('giraffe', 'zürafa', '1F992', 'animals', 'pre_a1_starters', false),
('goat', 'keçi', '1F410', 'animals', 'a1_movers', false),
('hippo', 'su aygırı', '1F99B', 'animals', 'pre_a1_starters', false),
('horse', 'at', '1F434', 'animals', 'pre_a1_starters', false),
('kangaroo', 'kanguru', '1F998', 'animals', 'a2_flyers', false),
('kitten', 'yavru kedi', '1F431', 'animals', 'a1_movers', false),
('lion', 'aslan', '1F981', 'animals', 'a1_movers', false),
('monkey', 'maymun', '1F435', 'animals', 'pre_a1_starters', false),
('mouse', 'fare', '1F42D', 'animals', 'pre_a1_starters', false),
('parrot', 'papağan', '1F99C', 'animals', 'a1_movers', false),
('penguin', 'penguen', '1F427', 'animals', 'a1_movers', false),
('puppy', 'yavru köpek', '1F436', 'animals', 'a1_movers', false),
('rabbit', 'tavşan', '1F430', 'animals', 'a1_movers', false),
('shark', 'köpek balığı', '1F988', 'animals', 'a1_movers', false),
('sheep', 'koyun', '1F411', 'animals', 'pre_a1_starters', false),
('snake', 'yılan', '1F40D', 'animals', 'pre_a1_starters', false),
('spider', 'örümcek', '1F577', 'animals', 'pre_a1_starters', false),
('tiger', 'kaplan', '1F42F', 'animals', 'a1_movers', false),
('turtle', 'kaplumbağa', '1F422', 'animals', 'a1_movers', false),
('whale', 'balina', '1F433', 'animals', 'a1_movers', false),
('zebra', 'zebra', '1F993', 'animals', 'a1_movers', false),
('butterfly', 'kelebek', '1F98B', 'animals', 'a2_flyers', false),
('camel', 'deve', '1F42B', 'animals', 'a2_flyers', false),
('pet', 'evcil hayvan', '1F43E', 'animals', 'a1_movers', false),
('arm', 'kol', '1F4AA', 'body', 'pre_a1_starters', false),
('back', 'sırt', '1F9CD', 'body', 'a1_movers', false),
('ear', 'kulak', '1F442', 'body', 'pre_a1_starters', false),
('eye', 'göz', '1F441', 'body', 'pre_a1_starters', false),
('face', 'yüz', '1F642', 'body', 'pre_a1_starters', false),
('finger', 'parmak', '261D', 'body', 'a1_movers', false),
('foot', 'ayak', '1F9B6', 'body', 'pre_a1_starters', false),
('hair', 'saç', '1F9D1', 'body', 'pre_a1_starters', false),
('hand', 'el', '270B', 'body', 'pre_a1_starters', false),
('head', 'baş', '1F9D1', 'body', 'pre_a1_starters', false),
('knee', 'diz', '1F9B5', 'body', 'a1_movers', false),
('leg', 'bacak', '1F9B5', 'body', 'pre_a1_starters', false),
('mouth', 'ağız', '1F444', 'body', 'pre_a1_starters', false),
('neck', 'boyun', '1F9CD', 'body', 'a1_movers', false),
('nose', 'burun', '1F443', 'body', 'pre_a1_starters', false),
('shoulder', 'omuz', '1F9CD', 'body', 'a2_flyers', false),
('stomach', 'mide', '1F912', 'body', 'a2_flyers', false),
('teeth', 'dişler', '1F9B7', 'body', 'a1_movers', false),
('thumb', 'baş parmak', '1F44D', 'body', 'a2_flyers', false),
('tongue', 'dil', '1F445', 'body', 'a2_flyers', false),
('bag', 'çanta', '1F45C', 'clothes', 'pre_a1_starters', false),
('boot', 'çizme', '1F97E', 'clothes', 'a1_movers', false),
('clothes', 'kıyafetler', '1F45A', 'clothes', 'a1_movers', false),
('coat', 'palto', '1F9E5', 'clothes', 'a1_movers', false),
('dress', 'elbise', '1F457', 'clothes', 'pre_a1_starters', false),
('glasses', 'gözlük', '1F453', 'clothes', 'a1_movers', false),
('glove', 'eldiven', '1F9E4', 'clothes', 'a2_flyers', false),
('handbag', 'el çantası', '1F45C', 'clothes', 'pre_a1_starters', false),
('hat', 'şapka', '1F9E2', 'clothes', 'pre_a1_starters', false),
('jacket', 'ceket', '1F9E5', 'clothes', 'pre_a1_starters', false),
('jeans', 'kot pantolon', '1F456', 'clothes', 'pre_a1_starters', false),
('scarf', 'atkı', '1F9E3', 'clothes', 'a1_movers', false),
('shirt', 'gömlek', '1F455', 'clothes', 'pre_a1_starters', false),
('shoe', 'ayakkabı', '1F45F', 'clothes', 'pre_a1_starters', false),
('skirt', 'etek', '1FA73', 'clothes', 'pre_a1_starters', false),
('sock', 'çorap', '1F9E6', 'clothes', 'pre_a1_starters', false),
('trousers', 'pantolon', '1F456', 'clothes', 'pre_a1_starters', false),
('umbrella', 'şemsiye', '2602', 'clothes', 'a1_movers', false),
('black', 'siyah', '26AB', 'colours', 'pre_a1_starters', false),
('blue', 'mavi', '1F535', 'colours', 'pre_a1_starters', false),
('brown', 'kahverengi', '1F7EB', 'colours', 'pre_a1_starters', false),
('green', 'yeşil', '1F7E2', 'colours', 'pre_a1_starters', false),
('grey', 'gri', '26AA', 'colours', 'pre_a1_starters', false),
('orange', 'turuncu', '1F7E0', 'colours', 'pre_a1_starters', false),
('pink', 'pembe', '1F338', 'colours', 'pre_a1_starters', false),
('purple', 'mor', '1F7E3', 'colours', 'pre_a1_starters', false),
('red', 'kırmızı', '1F534', 'colours', 'pre_a1_starters', false),
('white', 'beyaz', '26AA', 'colours', 'pre_a1_starters', false),
('yellow', 'sarı', '1F7E1', 'colours', 'pre_a1_starters', false),
('gold', 'altın', '1F7E1', 'colours', 'a2_flyers', false),
('baby', 'bebek', '1F476', 'family', 'pre_a1_starters', true),
('boy', 'erkek çocuk', '1F466', 'family', 'pre_a1_starters', false),
('brother', 'erkek kardeş', '1F466', 'family', 'pre_a1_starters', true),
('child', 'çocuk', '1F9D2', 'family', 'a1_movers', false),
('cousin', 'kuzen', '1F9D1', 'family', 'a1_movers', true),
('dad', 'baba', '1F468', 'family', 'pre_a1_starters', true),
('family', 'aile', '1F46A', 'family', 'pre_a1_starters', true),
('friend', 'arkadaş', '1F91D', 'family', 'pre_a1_starters', true),
('girl', 'kız çocuk', '1F467', 'family', 'pre_a1_starters', false),
('grandma', 'büyükanne', '1F475', 'family', 'a1_movers', true),
('grandpa', 'büyükbaba', '1F474', 'family', 'a1_movers', true),
('mother', 'anne', '1F469', 'family', 'pre_a1_starters', true),
('father', 'baba', '1F468', 'family', 'pre_a1_starters', true),
('parent', 'ebeveyn', '1F46A', 'family', 'a1_movers', true),
('sister', 'kız kardeş', '1F467', 'family', 'pre_a1_starters', true),
('uncle', 'amca', '1F468', 'family', 'a1_movers', true),
('apple', 'elma', '1F34E', 'food', 'pre_a1_starters', false),
('banana', 'muz', '1F34C', 'food', 'pre_a1_starters', false),
('bean', 'fasulye', '1FAD8', 'food', 'pre_a1_starters', false),
('bread', 'ekmek', '1F35E', 'food', 'pre_a1_starters', false),
('butter', 'tereyağı', '1F9C8', 'food', 'a1_movers', false),
('cake', 'kek', '1F370', 'food', 'pre_a1_starters', false),
('candy', 'şeker', '1F36C', 'food', 'a1_movers', false),
('carrot', 'havuç', '1F955', 'food', 'pre_a1_starters', false),
('cheese', 'peynir', '1F9C0', 'food', 'a1_movers', false),
('cherry', 'kiraz', '1F352', 'food', 'a2_flyers', false),
('chocolate', 'çikolata', '1F36B', 'food', 'a1_movers', false),
('coconut', 'hindistan cevizi', '1F965', 'food', 'pre_a1_starters', false),
('egg', 'yumurta', '1F95A', 'food', 'pre_a1_starters', false),
('flour', 'un', '1F33E', 'food', 'a2_flyers', false),
('grape', 'üzüm', '1F347', 'food', 'a1_movers', false),
('ice cream', 'dondurma', '1F368', 'food', 'pre_a1_starters', false),
('juice', 'meyve suyu', '1F9C3', 'food', 'pre_a1_starters', false),
('lemon', 'limon', '1F34B', 'food', 'pre_a1_starters', false),
('mango', 'mango', '1F96D', 'food', 'pre_a1_starters', false),
('meat', 'et', '1F356', 'food', 'a1_movers', false),
('milk', 'süt', '1F95B', 'food', 'pre_a1_starters', false),
('mushroom', 'mantar', '1F344', 'food', 'a2_flyers', false),
('onion', 'soğan', '1F9C5', 'food', 'a1_movers', false),
('orange', 'portakal', '1F34A', 'food', 'pre_a1_starters', false),
('pasta', 'makarna', '1F35D', 'food', 'a2_flyers', false),
('pea', 'bezelye', '1FAD1', 'food', 'pre_a1_starters', false),
('pear', 'armut', '1F350', 'food', 'pre_a1_starters', false),
('pepper', 'biber', '1FAD1', 'food', 'a2_flyers', false),
('pineapple', 'ananas', '1F34D', 'food', 'pre_a1_starters', false),
('potato', 'patates', '1F954', 'food', 'a1_movers', false),
('rice', 'pilav', '1F35A', 'food', 'a1_movers', false),
('salad', 'salata', '1F957', 'food', 'a1_movers', false),
('sandwich', 'sandviç', '1F96A', 'food', 'a1_movers', false),
('soup', 'çorba', '1F958', 'food', 'a1_movers', false),
('strawberry', 'çilek', '1F353', 'food', 'a2_flyers', false),
('sugar', 'şeker', '1F36C', 'food', 'a2_flyers', false),
('tea', 'çay', '2615', 'food', 'a1_movers', false),
('tomato', 'domates', '1F345', 'food', 'a1_movers', false),
('water', 'su', '1F4A7', 'food', 'pre_a1_starters', false),
('watermelon', 'karpuz', '1F349', 'food', 'pre_a1_starters', false),
('bathroom', 'banyo', '1F6C1', 'home', 'pre_a1_starters', false),
('bed', 'yatak', '1F6CF', 'home', 'pre_a1_starters', false),
('bedroom', 'yatak odası', '1F6CF', 'home', 'pre_a1_starters', false),
('bookcase', 'kitaplık', '1F4DA', 'home', 'pre_a1_starters', false),
('chair', 'sandalye', '1FA91', 'home', 'pre_a1_starters', false),
('clock', 'saat', '1F570', 'home', 'pre_a1_starters', false),
('cupboard', 'dolap', '1F3E0', 'home', 'a1_movers', false),
('desk', 'masa', '1F4DD', 'home', 'pre_a1_starters', false),
('dining room', 'yemek odası', '1F37D', 'home', 'a1_movers', false),
('door', 'kapı', '1F6AA', 'home', 'pre_a1_starters', false),
('flat', 'daire', '1F3E2', 'home', 'a1_movers', false),
('floor', 'zemin', '1F3E0', 'home', 'a1_movers', false),
('fridge', 'buzdolabı', '1F9CA', 'home', 'a1_movers', false),
('garden', 'bahçe', '1F33B', 'home', 'pre_a1_starters', false),
('house', 'ev', '1F3E0', 'home', 'pre_a1_starters', false),
('kitchen', 'mutfak', '1F373', 'home', 'pre_a1_starters', false),
('lamp', 'lamba', '1F4A1', 'home', 'pre_a1_starters', false),
('living room', 'oturma odası', '1F6CB', 'home', 'a1_movers', false),
('mirror', 'ayna', '1FA9E', 'home', 'pre_a1_starters', false),
('phone', 'telefon', '1F4F1', 'home', 'pre_a1_starters', false),
('radio', 'radyo', '1F4FB', 'home', 'pre_a1_starters', false),
('roof', 'çatı', '1F3E0', 'home', 'a2_flyers', false),
('room', 'oda', '1F6AA', 'home', 'pre_a1_starters', false),
('sofa', 'kanepe', '1F6CB', 'home', 'a1_movers', false),
('stairs', 'merdiven', '1FA9C', 'home', 'a2_flyers', false),
('table', 'masa', '1F4DD', 'home', 'pre_a1_starters', false),
('television', 'televizyon', '1F4FA', 'home', 'pre_a1_starters', false),
('wall', 'duvar', '1F9F1', 'home', 'a1_movers', false),
('window', 'pencere', '1FA9F', 'home', 'pre_a1_starters', false),
('yard', 'avlu', '1F33F', 'home', 'a2_flyers', false),
('board', 'tahta', '1F4CB', 'school', 'pre_a1_starters', false),
('book', 'kitap', '1F4D6', 'school', 'pre_a1_starters', false),
('classroom', 'sınıf', '1F3EB', 'school', 'pre_a1_starters', false),
('computer', 'bilgisayar', '1F4BB', 'school', 'pre_a1_starters', false),
('crayon', 'boya kalemi', '1F58D', 'school', 'pre_a1_starters', false),
('desk', 'sıra', '1F4DD', 'school', 'pre_a1_starters', false),
('dictionary', 'sözlük', '1F4D5', 'school', 'a2_flyers', false),
('eraser', 'silgi', '1F4DD', 'school', 'pre_a1_starters', false),
('homework', 'ödev', '1F4DD', 'school', 'a1_movers', false),
('lesson', 'ders', '1F4D6', 'school', 'a1_movers', false),
('letter', 'harf', '1F524', 'school', 'pre_a1_starters', false),
('number', 'sayı', '1F522', 'school', 'pre_a1_starters', false),
('page', 'sayfa', '1F4C4', 'school', 'a1_movers', false),
('pen', 'tükenmez kalem', '1F58A', 'school', 'pre_a1_starters', false),
('pencil', 'kurşun kalem', '270F', 'school', 'pre_a1_starters', false),
('picture', 'resim', '1F5BC', 'school', 'pre_a1_starters', false),
('ruler', 'cetvel', '1F4CF', 'school', 'pre_a1_starters', false),
('school', 'okul', '1F3EB', 'school', 'pre_a1_starters', false),
('teacher', 'öğretmen', '1F9D1', 'school', 'pre_a1_starters', false),
('word', 'kelime', '1F524', 'school', 'a1_movers', false),
('ball', 'top', '26BD', 'sports', 'pre_a1_starters', false),
('basketball', 'basketbol', '1F3C0', 'sports', 'pre_a1_starters', false),
('beach', 'kumsal', '1F3D6', 'sports', 'pre_a1_starters', false),
('bike', 'bisiklet', '1F6B2', 'sports', 'pre_a1_starters', false),
('camera', 'kamera', '1F4F7', 'sports', 'pre_a1_starters', false),
('football', 'futbol', '26BD', 'sports', 'pre_a1_starters', false),
('game', 'oyun', '1F3AE', 'sports', 'a1_movers', false),
('guitar', 'gitar', '1F3B8', 'sports', 'a1_movers', false),
('kite', 'uçurtma', '1FA81', 'sports', 'pre_a1_starters', false),
('movie', 'film', '1F3AC', 'sports', 'a2_flyers', false),
('painting', 'resim', '1F3A8', 'sports', 'a1_movers', false),
('park', 'park', '1F3DE', 'sports', 'a1_movers', false),
('piano', 'piyano', '1F3B9', 'sports', 'a1_movers', false),
('playground', 'oyun alanı', '1F3A0', 'sports', 'a1_movers', false),
('race', 'yarış', '1F3C3', 'sports', 'a2_flyers', false),
('song', 'şarkı', '1F3B5', 'sports', 'a1_movers', false),
('sport', 'spor', '26BD', 'sports', 'a1_movers', false),
('story', 'hikaye', '1F4D6', 'sports', 'a1_movers', false),
('swimming pool', 'yüzme havuzu', '1F3CA', 'sports', 'a1_movers', false),
('tennis', 'tenis', '1F3BE', 'sports', 'pre_a1_starters', false),
('boat', 'tekne', '26F5', 'transport', 'pre_a1_starters', false),
('bus', 'otobüs', '1F68C', 'transport', 'pre_a1_starters', false),
('car', 'araba', '1F697', 'transport', 'pre_a1_starters', false),
('helicopter', 'helikopter', '1F681', 'transport', 'pre_a1_starters', false),
('lorry', 'kamyon', '1F69A', 'transport', 'pre_a1_starters', false),
('motorbike', 'motosiklet', '1F3CD', 'transport', 'a1_movers', false),
('plane', 'uçak', '2708', 'transport', 'pre_a1_starters', false),
('rocket', 'roket', '1F680', 'transport', 'a2_flyers', false),
('ship', 'gemi', '1F6A2', 'transport', 'a1_movers', false),
('taxi', 'taksi', '1F695', 'transport', 'a2_flyers', false),
('train', 'tren', '1F682', 'transport', 'pre_a1_starters', false),
('truck', 'kamyon', '1F69A', 'transport', 'a1_movers', false),
('cloud', 'bulut', '2601', 'nature', 'a1_movers', false),
('field', 'tarla', '1F33E', 'nature', 'a2_flyers', false),
('flower', 'çiçek', '1F33C', 'nature', 'pre_a1_starters', false),
('forest', 'orman', '1F332', 'nature', 'a2_flyers', false),
('grass', 'çimen', '1F33F', 'nature', 'a1_movers', false),
('hill', 'tepe', '26F0', 'nature', 'a2_flyers', false),
('island', 'ada', '1F3DD', 'nature', 'a2_flyers', false),
('lake', 'göl', '1F30A', 'nature', 'a2_flyers', false),
('moon', 'ay', '1F319', 'nature', 'a1_movers', false),
('mountain', 'dağ', '26F0', 'nature', 'a2_flyers', false),
('rain', 'yağmur', '1F327', 'nature', 'pre_a1_starters', false),
('rainbow', 'gökkuşağı', '1F308', 'nature', 'a1_movers', false),
('river', 'nehir', '1F3DE', 'nature', 'a2_flyers', false),
('sea', 'deniz', '1F30A', 'nature', 'pre_a1_starters', false),
('snow', 'kar', '2744', 'nature', 'pre_a1_starters', false),
('star', 'yıldız', '2B50', 'nature', 'pre_a1_starters', false),
('sun', 'güneş', '2600', 'nature', 'pre_a1_starters', false),
('tree', 'ağaç', '1F333', 'nature', 'pre_a1_starters', false),
('one', 'bir', '0031-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('two', 'iki', '0032-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('three', 'üç', '0033-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('four', 'dört', '0034-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('five', 'beş', '0035-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('six', 'altı', '0036-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('seven', 'yedi', '0037-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('eight', 'sekiz', '0038-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('nine', 'dokuz', '0039-FE0F-20E3', 'numbers', 'pre_a1_starters', false),
('ten', 'on', '1F51F', 'numbers', 'pre_a1_starters', false),
('climb', 'tırmanmak', '1F9D7', 'actions', 'a1_movers', false),
('cook', 'pişirmek', '1F373', 'actions', 'a1_movers', false),
('dance', 'dans etmek', '1F483', 'actions', 'a1_movers', false),
('draw', 'çizmek', '1F58D', 'actions', 'pre_a1_starters', false),
('drink', 'içmek', '1F964', 'actions', 'pre_a1_starters', false),
('eat', 'yemek', '1F37D', 'actions', 'pre_a1_starters', false),
('fly', 'uçmak', '1F985', 'actions', 'pre_a1_starters', false),
('help', 'yardım etmek', '1F91D', 'actions', 'pre_a1_starters', true),
('jump', 'zıplamak', '1F938', 'actions', 'pre_a1_starters', false),
('kick', 'tekmelemek', '26BD', 'actions', 'pre_a1_starters', false),
('laugh', 'gülmek', '1F602', 'actions', 'a1_movers', false),
('learn', 'öğrenmek', '1F4D6', 'actions', 'a1_movers', false),
('listen', 'dinlemek', '1F442', 'actions', 'pre_a1_starters', false),
('paint', 'boyamak', '1F3A8', 'actions', 'pre_a1_starters', false),
('play', 'oynamak', '1F3AE', 'actions', 'pre_a1_starters', false),
('read', 'okumak', '1F4D6', 'actions', 'pre_a1_starters', false),
('ride', 'sürmek', '1F6B2', 'actions', 'pre_a1_starters', false),
('run', 'koşmak', '1F3C3', 'actions', 'pre_a1_starters', false),
('share', 'paylaşmak', '1F91D', 'actions', 'pre_a1_starters', true),
('sing', 'şarkı söylemek', '1F3A4', 'actions', 'pre_a1_starters', false),
('sit', 'oturmak', '1FA91', 'actions', 'pre_a1_starters', false),
('sleep', 'uyumak', '1F634', 'actions', 'pre_a1_starters', false),
('smile', 'gülümsemek', '1F60A', 'actions', 'pre_a1_starters', false),
('stand', 'ayakta durmak', '1F9CD', 'actions', 'pre_a1_starters', false),
('swim', 'yüzmek', '1F3CA', 'actions', 'pre_a1_starters', false),
('throw', 'fırlatmak', '1F938', 'actions', 'pre_a1_starters', false),
('walk', 'yürümek', '1F6B6', 'actions', 'pre_a1_starters', false),
('wash', 'yıkamak', '1F9FC', 'actions', 'pre_a1_starters', false),
('watch', 'izlemek', '1F440', 'actions', 'pre_a1_starters', false),
('write', 'yazmak', '270D', 'actions', 'pre_a1_starters', false),
('kind', 'nazik', '1F970', 'values', 'pre_a1_starters', true),
('honest', 'dürüst', '1F91D', 'values', 'a1_movers', true),
('respect', 'saygı', '1F64F', 'values', 'a1_movers', true),
('thank you', 'teşekkür ederim', '1F64F', 'values', 'pre_a1_starters', true),
('please', 'lütfen', '1F64F', 'values', 'pre_a1_starters', true),
('sorry', 'özür dilerim', '1F625', 'values', 'pre_a1_starters', true),
('brave', 'cesur', '1F4AA', 'values', 'a2_flyers', true),
('careful', 'dikkatli', '1F9D0', 'values', 'a2_flyers', true),
('balloon', 'balon', '1F388', 'toys', 'pre_a1_starters', false),
('board game', 'kutu oyunu', '1F3B2', 'toys', 'pre_a1_starters', false),
('doll', 'bebek', '1F9F8', 'toys', 'pre_a1_starters', false),
('drum', 'davul', '1F941', 'toys', 'a1_movers', false),
('robot', 'robot', '1F916', 'toys', 'pre_a1_starters', false),
('skateboard', 'kaykay', '1F6F9', 'toys', 'a1_movers', false),
('teddy bear', 'oyuncak ayı', '1F9F8', 'toys', 'a2_flyers', false),
('toy', 'oyuncak', '1F9F8', 'toys', 'pre_a1_starters', false),
('train', 'oyuncak tren', '1F682', 'toys', 'pre_a1_starters', false),
('puzzle', 'yapboz', '1F9E9', 'toys', 'a2_flyers', false);
