-- Generated from lib/data/vocabulary_words.csv - do not edit by hand
-- Run this AFTER migration 20260221100000_vocabulary_translations.sql

DELETE FROM vocabulary_words;

INSERT INTO vocabulary_words (word, openmoji_hex, category, level, is_cultural_value, translations)
VALUES
('cat', '1F431', 'animals', 'pre_a1_starters', false, '{"tr":"kedi","az":"pişik","es":"gato","en":"cat"}'::jsonb),
('dog', '1F436', 'animals', 'pre_a1_starters', false, '{"tr":"köpek","az":"it","es":"perro","en":"dog"}'::jsonb),
('bird', '1F426', 'animals', 'pre_a1_starters', false, '{"tr":"kuş","az":"quş","es":"pájaro","en":"bird"}'::jsonb),
('fish', '1F41F', 'animals', 'pre_a1_starters', false, '{"tr":"balık","az":"balıq","es":"pez","en":"fish"}'::jsonb),
('cow', '1F404', 'animals', 'pre_a1_starters', false, '{"tr":"inek","az":"inək","es":"vaca","en":"cow"}'::jsonb),
('horse', '1F40E', 'animals', 'a1_movers', false, '{"tr":"at","az":"at","es":"caballo","en":"horse"}'::jsonb),
('elephant', '1F418', 'animals', 'a1_movers', false, '{"tr":"fil","az":"fil","es":"elefante","en":"elephant"}'::jsonb),
('monkey', '1F412', 'animals', 'a1_movers', false, '{"tr":"maymun","az":"meymun","es":"mono","en":"monkey"}'::jsonb),
('lion', '1F981', 'animals', 'a2_flyers', false, '{"tr":"aslan","az":"şir","es":"león","en":"lion"}'::jsonb),
('bear', '1F43B', 'animals', 'a1_movers', false, '{"tr":"ayı","az":"ayı","es":"oso","en":"bear"}'::jsonb),
('head', '1F464', 'body', 'pre_a1_starters', false, '{"tr":"baş","az":"baş","es":"cabeza","en":"head"}'::jsonb),
('eye', '1F441', 'body', 'pre_a1_starters', false, '{"tr":"göz","az":"göz","es":"ojo","en":"eye"}'::jsonb),
('ear', '1F442', 'body', 'pre_a1_starters', false, '{"tr":"kulak","az":"qulaq","es":"oreja","en":"ear"}'::jsonb),
('nose', '1F443', 'body', 'pre_a1_starters', false, '{"tr":"burun","az":"burun","es":"nariz","en":"nose"}'::jsonb),
('mouth', '1F444', 'body', 'pre_a1_starters', false, '{"tr":"ağız","az":"ağız","es":"boca","en":"mouth"}'::jsonb),
('hand', '1F91A', 'body', 'pre_a1_starters', false, '{"tr":"el","az":"əl","es":"mano","en":"hand"}'::jsonb),
('leg', '1F9B5', 'body', 'pre_a1_starters', false, '{"tr":"bacak","az":"qıç","es":"pierna","en":"leg"}'::jsonb),
('foot', '1F9B6', 'body', 'pre_a1_starters', false, '{"tr":"ayak","az":"ayaq","es":"pie","en":"foot"}'::jsonb),
('shoulder', '1F9B4', 'body', 'a1_movers', false, '{"tr":"omuz","az":"çiyin","es":"hombro","en":"shoulder"}'::jsonb),
('back', '1F450', 'body', 'a1_movers', false, '{"tr":"sırt","az":"kürək","es":"espalda","en":"back"}'::jsonb),
('shirt', '1F455', 'clothes', 'pre_a1_starters', false, '{"tr":"gömlek","az":"köynək","es":"camisa","en":"shirt"}'::jsonb),
('t-shirt', '1F455', 'clothes', 'pre_a1_starters', false, '{"tr":"tişört","az":"tişört","es":"camiseta","en":"t-shirt"}'::jsonb),
('trousers', '1F456', 'clothes', 'pre_a1_starters', false, '{"tr":"pantolon","az":"şalvar","es":"pantalones","en":"trousers"}'::jsonb),
('dress', '1F457', 'clothes', 'pre_a1_starters', false, '{"tr":"elbise","az":"don","es":"vestido","en":"dress"}'::jsonb),
('shoe', '1F45E', 'clothes', 'pre_a1_starters', false, '{"tr":"ayakkabı","az":"ayaqqabı","es":"zapato","en":"shoe"}'::jsonb),
('sock', '1F9E6', 'clothes', 'a1_movers', false, '{"tr":"çorap","az":"corab","es":"calcetín","en":"sock"}'::jsonb),
('hat', '1F3A9', 'clothes', 'pre_a1_starters', false, '{"tr":"şapka","az":"papaq","es":"sombrero","en":"hat"}'::jsonb),
('coat', '1F9E5', 'clothes', 'a1_movers', false, '{"tr":"palto","az":"palto","es":"abrigo","en":"coat"}'::jsonb),
('scarf', '1F9E3', 'clothes', 'a1_movers', false, '{"tr":"atkı","az":"şərf","es":"bufanda","en":"scarf"}'::jsonb),
('glove', '1F9E4', 'clothes', 'a2_flyers', false, '{"tr":"eldiven","az":"əlcək","es":"guante","en":"glove"}'::jsonb),
('red', '1F534', 'colours', 'pre_a1_starters', false, '{"tr":"kırmızı","az":"qırmızı","es":"rojo","en":"red"}'::jsonb),
('blue', '1F535', 'colours', 'pre_a1_starters', false, '{"tr":"mavi","az":"mavi","es":"azul","en":"blue"}'::jsonb),
('green', '1F7E2', 'colours', 'pre_a1_starters', false, '{"tr":"yeşil","az":"yaşıl","es":"verde","en":"green"}'::jsonb),
('yellow', '1F7E1', 'colours', 'pre_a1_starters', false, '{"tr":"sarı","az":"sarı","es":"amarillo","en":"yellow"}'::jsonb),
('black', '2B1B', 'colours', 'pre_a1_starters', false, '{"tr":"siyah","az":"qara","es":"negro","en":"black"}'::jsonb),
('white', '2B1C', 'colours', 'pre_a1_starters', false, '{"tr":"beyaz","az":"ağ","es":"blanco","en":"white"}'::jsonb),
('pink', '1F531', 'colours', 'pre_a1_starters', false, '{"tr":"pembe","az":"çəhrayı","es":"rosa","en":"pink"}'::jsonb),
('purple', '1F7E3', 'colours', 'pre_a1_starters', false, '{"tr":"mor","az":"bənövşəyi","es":"morado","en":"purple"}'::jsonb),
('orange', '1F7E0', 'colours', 'pre_a1_starters', false, '{"tr":"turuncu","az":"narıncı","es":"naranja","en":"orange"}'::jsonb),
('brown', '1F7EB', 'colours', 'pre_a1_starters', false, '{"tr":"kahverengi","az":"qəhvəyi","es":"marrón","en":"brown"}'::jsonb),
('apple', '1F34E', 'food', 'pre_a1_starters', false, '{"tr":"elma","az":"alma","es":"manzana","en":"apple"}'::jsonb),
('banana', '1F34C', 'food', 'pre_a1_starters', false, '{"tr":"muz","az":"banan","es":"plátano","en":"banana"}'::jsonb),
('bread', '1F35E', 'food', 'pre_a1_starters', false, '{"tr":"ekmek","az":"çörək","es":"pan","en":"bread"}'::jsonb),
('water', '1F4A7', 'food', 'pre_a1_starters', false, '{"tr":"su","az":"su","es":"agua","en":"water"}'::jsonb),
('milk', '1F95B', 'food', 'pre_a1_starters', false, '{"tr":"süt","az":"süd","es":"leche","en":"milk"}'::jsonb),
('cheese', '1F9C0', 'food', 'a1_movers', false, '{"tr":"peynir","az":"pendir","es":"queso","en":"cheese"}'::jsonb),
('chicken', '1F357', 'food', 'pre_a1_starters', false, '{"tr":"tavuk","az":"toyuq","es":"pollo","en":"chicken"}'::jsonb),
('egg', '1F95A', 'food', 'pre_a1_starters', false, '{"tr":"yumurta","az":"yumurta","es":"huevo","en":"egg"}'::jsonb),
('cake', '1F370', 'food', 'pre_a1_starters', false, '{"tr":"pasta","az":"tort","es":"pastel","en":"cake"}'::jsonb),
('juice', '1F9C3', 'food', 'pre_a1_starters', false, '{"tr":"meyve suyu","az":"meyvə şirəsi","es":"jugo","en":"juice"}'::jsonb),
('house', '1F3E0', 'home', 'pre_a1_starters', false, '{"tr":"ev","az":"ev","es":"casa","en":"house"}'::jsonb),
('room', '1F6AA', 'home', 'pre_a1_starters', false, '{"tr":"oda","az":"otaq","es":"habitación","en":"room"}'::jsonb),
('bed', '1F6CF', 'home', 'pre_a1_starters', false, '{"tr":"yatak","az":"yataq","es":"cama","en":"bed"}'::jsonb),
('table', '1F6E0', 'home', 'pre_a1_starters', false, '{"tr":"masa","az":"masa","es":"mesa","en":"table"}'::jsonb),
('chair', '1FA91', 'home', 'pre_a1_starters', false, '{"tr":"sandalye","az":"stul","es":"silla","en":"chair"}'::jsonb),
('kitchen', '1F373', 'home', 'pre_a1_starters', false, '{"tr":"mutfak","az":"mətbəx","es":"cocina","en":"kitchen"}'::jsonb),
('bathroom', '1F6C1', 'home', 'pre_a1_starters', false, '{"tr":"banyo","az":"hamam","es":"baño","en":"bathroom"}'::jsonb),
('window', '1FA9F', 'home', 'pre_a1_starters', false, '{"tr":"pencere","az":"pəncərə","es":"ventana","en":"window"}'::jsonb),
('door', '1F6AA', 'home', 'pre_a1_starters', false, '{"tr":"kapı","az":"qapı","es":"puerta","en":"door"}'::jsonb),
('clock', '1F552', 'home', 'pre_a1_starters', false, '{"tr":"saat","az":"saat","es":"reloj","en":"clock"}'::jsonb),
('sun', '2600', 'nature', 'pre_a1_starters', false, '{"tr":"güneş","az":"günəş","es":"sol","en":"sun"}'::jsonb),
('moon', '1F319', 'nature', 'pre_a1_starters', false, '{"tr":"ay","az":"ay","es":"luna","en":"moon"}'::jsonb),
('star', '2B50', 'nature', 'pre_a1_starters', false, '{"tr":"yıldız","az":"ulduz","es":"estrella","en":"star"}'::jsonb),
('tree', '1F333', 'nature', 'pre_a1_starters', false, '{"tr":"ağaç","az":"ağac","es":"árbol","en":"tree"}'::jsonb),
('flower', '1F33C', 'nature', 'pre_a1_starters', false, '{"tr":"çiçek","az":"çiçək","es":"flor","en":"flower"}'::jsonb),
('sea', '1F30A', 'nature', 'pre_a1_starters', false, '{"tr":"deniz","az":"dəniz","es":"mar","en":"sea"}'::jsonb),
('rain', '1F327', 'nature', 'a1_movers', false, '{"tr":"yağmur","az":"yağış","es":"lluvia","en":"rain"}'::jsonb),
('snow', '2744', 'nature', 'a1_movers', false, '{"tr":"kar","az":"qar","es":"nieve","en":"snow"}'::jsonb),
('mountain', '26F0', 'nature', 'a1_movers', false, '{"tr":"dağ","az":"dağ","es":"montaña","en":"mountain"}'::jsonb),
('river', '1F30D', 'nature', 'a1_movers', false, '{"tr":"nehir","az":"çay","es":"río","en":"river"}'::jsonb),
('book', '1F4D6', 'school', 'pre_a1_starters', false, '{"tr":"kitap","az":"kitab","es":"libro","en":"book"}'::jsonb),
('pen', '1F58A', 'school', 'pre_a1_starters', false, '{"tr":"tükenmez kalem","az":"qələm","es":"bolígrafo","en":"pen"}'::jsonb),
('pencil', '270F', 'school', 'pre_a1_starters', false, '{"tr":"kurşun kalem","az":"karandaş","es":"lápiz","en":"pencil"}'::jsonb),
('rubber', '1F9FD', 'school', 'pre_a1_starters', false, '{"tr":"silgi","az":"pozan","es":"goma","en":"rubber"}'::jsonb),
('ruler', '1F4CF', 'school', 'pre_a1_starters', false, '{"tr":"cetvel","az":"xətkeş","es":"regla","en":"ruler"}'::jsonb),
('bag', '1F392', 'school', 'pre_a1_starters', false, '{"tr":"çanta","az":"çanta","es":"mochila","en":"bag"}'::jsonb),
('teacher', '1F9D1', 'school', 'pre_a1_starters', false, '{"tr":"öğretmen","az":"müəllim","es":"profesor","en":"teacher"}'::jsonb),
('student', '1F393', 'school', 'pre_a1_starters', false, '{"tr":"öğrenci","az":"şagird","es":"estudiante","en":"student"}'::jsonb),
('board', '1F4CB', 'school', 'pre_a1_starters', false, '{"tr":"tahta","az":"lövhə","es":"pizarra","en":"board"}'::jsonb),
('computer', '1F4BB', 'school', 'pre_a1_starters', false, '{"tr":"bilgisayar","az":"kompüter","es":"ordenador","en":"computer"}'::jsonb),
('car', '1F697', 'transport', 'pre_a1_starters', false, '{"tr":"araba","az":"maşın","es":"coche","en":"car"}'::jsonb),
('bus', '1F68C', 'transport', 'pre_a1_starters', false, '{"tr":"otobüs","az":"avtobus","es":"autobús","en":"bus"}'::jsonb),
('train', '1F686', 'transport', 'pre_a1_starters', false, '{"tr":"tren","az":"qatar","es":"tren","en":"train"}'::jsonb),
('plane', '2708', 'transport', 'pre_a1_starters', false, '{"tr":"uçak","az":"təyyarə","es":"avión","en":"plane"}'::jsonb),
('boat', '26F5', 'transport', 'pre_a1_starters', false, '{"tr":"tekne","az":"qayıq","es":"barco","en":"boat"}'::jsonb),
('bike', '1F6B2', 'transport', 'pre_a1_starters', false, '{"tr":"bisiklet","az":"velosiped","es":"bicicleta","en":"bike"}'::jsonb),
('helicopter', '1F681', 'transport', 'a1_movers', false, '{"tr":"helikopter","az":"helikopter","es":"helicóptero","en":"helicopter"}'::jsonb),
('taxi', '1F695', 'transport', 'a2_flyers', false, '{"tr":"taksi","az":"taksi","es":"taxi","en":"taxi"}'::jsonb),
('lorry', '1F69A', 'transport', 'a1_movers', false, '{"tr":"kamyon","az":"yük maşını","es":"camión","en":"lorry"}'::jsonb),
('tractor', '1F69C', 'transport', 'a1_movers', false, '{"tr":"traktör","az":"traktor","es":"tractor","en":"tractor"}'::jsonb),
('doll', '1F38E', 'toys', 'pre_a1_starters', false, '{"tr":"oyuncak bebek","az":"gəlincik","es":"muñeca","en":"doll"}'::jsonb),
('ball', '26BD', 'toys', 'pre_a1_starters', false, '{"tr":"top","az":"top","es":"pelota","en":"ball"}'::jsonb),
('kite', '1FA81', 'toys', 'pre_a1_starters', false, '{"tr":"uçurtma","az":"çərpələng","es":"cometa","en":"kite"}'::jsonb),
('robot', '1F916', 'toys', 'pre_a1_starters', false, '{"tr":"robot","az":"robot","es":"robot","en":"robot"}'::jsonb),
('puzzle', '1F9E9', 'toys', 'a1_movers', false, '{"tr":"yapboz","az":"tapmaca","es":"rompecabezas","en":"puzzle"}'::jsonb),
('kind', '1F932', 'values', 'a1_movers', true, '{"tr":"nazik","az":"mehriban","es":"amable","en":"kind"}'::jsonb),
('share', '1F91D', 'values', 'a1_movers', true, '{"tr":"paylaşmak","az":"bölüşmək","es":"compartir","en":"share"}'::jsonb),
('honest', '1F90D', 'values', 'a2_flyers', true, '{"tr":"dürüst","az":"dürüst","es":"honesto","en":"honest"}'::jsonb),
('respect', '1F64F', 'values', 'a2_flyers', true, '{"tr":"saygı","az":"hörmət","es":"respeto","en":"respect"}'::jsonb),
('help', '1F91D', 'values', 'a1_movers', true, '{"tr":"yardım etmek","az":"kömək etmək","es":"ayudar","en":"help"}'::jsonb),
('tiger', '1F42F', 'animals', 'pre_a1_starters', false, '{"tr":"kaplan","az":"pələng","es":"tigre","en":"tiger"}'::jsonb),
('crocodile', '1F40A', 'animals', 'pre_a1_starters', false, '{"tr":"timsah","az":"timsah","es":"cocodrilo","en":"crocodile"}'::jsonb),
('snake', '1F40D', 'animals', 'pre_a1_starters', false, '{"tr":"yılan","az":"ilan","es":"serpiente","en":"snake"}'::jsonb),
('spider', '1F577', 'animals', 'pre_a1_starters', false, '{"tr":"örümcek","az":"hörümçək","es":"araña","en":"spider"}'::jsonb),
('frog', '1F438', 'animals', 'pre_a1_starters', false, '{"tr":"kurbağa","az":"qurbağa","es":"rana","en":"frog"}'::jsonb),
('hippo', '1F99B', 'animals', 'pre_a1_starters', false, '{"tr":"su aygırı","az":"begemot","es":"hipopótamo","en":"hippo"}'::jsonb),
('giraffe', '1F992', 'animals', 'pre_a1_starters', false, '{"tr":"zürafa","az":"zürafə","es":"jirafa","en":"giraffe"}'::jsonb),
('zebra', '1F993', 'animals', 'pre_a1_starters', false, '{"tr":"zebra","az":"zebra","es":"cebra","en":"zebra"}'::jsonb),
('rabbit', '1F430', 'animals', 'a1_movers', false, '{"tr":"tavşan","az":"dovşan","es":"conejo","en":"rabbit"}'::jsonb),
('mouse', '1F42D', 'animals', 'pre_a1_starters', false, '{"tr":"fare","az":"siçan","es":"ratón","en":"mouse"}'::jsonb),
('tomato', '1F345', 'food', 'pre_a1_starters', false, '{"tr":"domates","az":"pomidor","es":"tomate","en":"tomato"}'::jsonb),
('potato', '1F954', 'food', 'pre_a1_starters', false, '{"tr":"patates","az":"kartof","es":"papa","en":"potato"}'::jsonb),
('onion', '1F9C5', 'food', 'a1_movers', false, '{"tr":"soğan","az":"soğan","es":"cebolla","en":"onion"}'::jsonb),
('carrot', '1F955', 'food', 'pre_a1_starters', false, '{"tr":"havuç","az":"kök","es":"zanahoria","en":"carrot"}'::jsonb),
('burger', '1F354', 'food', 'pre_a1_starters', false, '{"tr":"hamburger","az":"hamburger","es":"hamburguesa","en":"burger"}'::jsonb),
('pizza', '1F355', 'food', 'pre_a1_starters', false, '{"tr":"pizza","az":"pizza","es":"pizza","en":"pizza"}'::jsonb),
('ice cream', '1F368', 'food', 'pre_a1_starters', false, '{"tr":"dondurma","az":"dondurma","es":"helado","en":"ice cream"}'::jsonb),
('chocolate', '1F36B', 'food', 'a1_movers', false, '{"tr":"çikolata","az":"şokolad","es":"chocolate","en":"chocolate"}'::jsonb),
('rice', '1F35A', 'food', 'pre_a1_starters', false, '{"tr":"pirinç","az":"düyü","es":"arroz","en":"rice"}'::jsonb),
('soup', '1F372', 'food', 'a1_movers', false, '{"tr":"çorba","az":"şorba","es":"sopa","en":"soup"}'::jsonb),
('hair', '1F9B0', 'body', 'pre_a1_starters', false, '{"tr":"saç","az":"saç","es":"cabello","en":"hair"}'::jsonb),
('face', '1F600', 'body', 'pre_a1_starters', false, '{"tr":"yüz","az":"üz","es":"cara","en":"face"}'::jsonb),
('neck', '1F9D1', 'body', 'a1_movers', false, '{"tr":"boyun","az":"boyun","es":"cuello","en":"neck"}'::jsonb),
('arm', '1F4AA', 'body', 'pre_a1_starters', false, '{"tr":"kol","az":"qol","es":"brazo","en":"arm"}'::jsonb),
('stomach', '1F9C3', 'body', 'a1_movers', false, '{"tr":"mide","az":"mədə","es":"estómago","en":"stomach"}'::jsonb),
('tooth', '1F9B7', 'body', 'a1_movers', false, '{"tr":"diş","az":"diş","es":"diente","en":"tooth"}'::jsonb),
('finger', '1F446', 'body', 'a1_movers', false, '{"tr":"parmak","az":"barmaq","es":"dedo","en":"finger"}'::jsonb),
('toe', '1F9B6', 'body', 'a1_movers', false, '{"tr":"ayak parmağı","az":"ayaq barmağı","es":"dedo del pie","en":"toe"}'::jsonb),
('knee', '1F9B5', 'body', 'a1_movers', false, '{"tr":"diz","az":"diz","es":"rodilla","en":"knee"}'::jsonb),
('tongue', '1F445', 'body', 'a1_movers', false, '{"tr":"dil","az":"dil","es":"lengua","en":"tongue"}'::jsonb),
('skirt', '1F454', 'clothes', 'pre_a1_starters', false, '{"tr":"etek","az":"ətək","es":"falda","en":"skirt"}'::jsonb),
('jacket', '1F9E5', 'clothes', 'pre_a1_starters', false, '{"tr":"ceket","az":"gödəkcə","es":"chaqueta","en":"jacket"}'::jsonb),
('sweater', '1F9E5', 'clothes', 'a1_movers', false, '{"tr":"kazak","az":"sviter","es":"suéter","en":"sweater"}'::jsonb),
('jeans', '1F456', 'clothes', 'pre_a1_starters', false, '{"tr":"kot pantolon","az":"cins şalvar","es":"vaqueros","en":"jeans"}'::jsonb),
('shorts', '1FA73', 'clothes', 'pre_a1_starters', false, '{"tr":"şort","az":"şort","es":"pantalones cortos","en":"shorts"}'::jsonb),
('glasses', '1F453', 'clothes', 'pre_a1_starters', false, '{"tr":"gözlük","az":"eynək","es":"gafas","en":"glasses"}'::jsonb),
('swimsuit', '1F459', 'clothes', 'a2_flyers', false, '{"tr":"mayo","az":"çimərlik geyimi","es":"traje de baño","en":"swimsuit"}'::jsonb),
('boots', '1F462', 'clothes', 'a1_movers', false, '{"tr":"bot","az":"çəkmə","es":"botas","en":"boots"}'::jsonb),
('cap', '1F9E2', 'clothes', 'pre_a1_starters', false, '{"tr":"şapka","az":"papaq","es":"gorra","en":"cap"}'::jsonb),
('wall', '1F9F1', 'home', 'a1_movers', false, '{"tr":"duvar","az":"divar","es":"pared","en":"wall"}'::jsonb),
('floor', '1F6E0', 'home', 'a1_movers', false, '{"tr":"zemin","az":"döşəmə","es":"suelo","en":"floor"}'::jsonb),
('roof', '1F3E0', 'home', 'a1_movers', false, '{"tr":"çatı","az":"dam","es":"techo","en":"roof"}'::jsonb),
('garden', '1F3DE', 'home', 'pre_a1_starters', false, '{"tr":"bahçe","az":"bağça","es":"jardín","en":"garden"}'::jsonb),
('living room', '1F6CB', 'home', 'pre_a1_starters', false, '{"tr":"oturma odası","az":"qonaq otağı","es":"sala de estar","en":"living room"}'::jsonb),
('dining room', '1F37D', 'home', 'pre_a1_starters', false, '{"tr":"yemek odası","az":"yemək otağı","es":"comedor","en":"dining room"}'::jsonb),
('hall', '1F6AA', 'home', 'pre_a1_starters', false, '{"tr":"koridor","az":"dəhliz","es":"pasillo","en":"hall"}'::jsonb),
('stairs', '1FA9C', 'home', 'a1_movers', false, '{"tr":"merdiven","az":"pilləkən","es":"escaleras","en":"stairs"}'::jsonb),
('sofa', '1F6CB', 'home', 'pre_a1_starters', false, '{"tr":"kanepe","az":"divan","es":"sofá","en":"sofa"}'::jsonb),
('armchair', '1FA91', 'home', 'pre_a1_starters', false, '{"tr":"koltuk","az":"kreslo","es":"sillón","en":"armchair"}'::jsonb),
('plant', '1F33F', 'nature', 'a1_movers', false, '{"tr":"bitki","az":"bitki","es":"planta","en":"plant"}'::jsonb),
('grass', '1F33F', 'nature', 'a1_movers', false, '{"tr":"çimen","az":"ot","es":"hierba","en":"grass"}'::jsonb),
('sand', '1F3DD', 'nature', 'pre_a1_starters', false, '{"tr":"kum","az":"qum","es":"arena","en":"sand"}'::jsonb),
('beach', '1F3D6', 'nature', 'pre_a1_starters', false, '{"tr":"plaj","az":"çimərlik","es":"playa","en":"beach"}'::jsonb),
('shell', '1F41A', 'nature', 'pre_a1_starters', false, '{"tr":"deniz kabuğu","az":"balıqqulağı","es":"concha","en":"shell"}'::jsonb),
('rock', '1FAA8', 'nature', 'a1_movers', false, '{"tr":"kaya","az":"qaya","es":"roca","en":"rock"}'::jsonb),
('island', '1F3DD', 'nature', 'a1_movers', false, '{"tr":"ada","az":"ada","es":"isla","en":"island"}'::jsonb),
('jungle', '1F334', 'nature', 'a1_movers', false, '{"tr":"orman","az":"cəngəllik","es":"selva","en":"jungle"}'::jsonb),
('field', '1F3FE', 'nature', 'a1_movers', false, '{"tr":"tarla","az":"tarla","es":"campo","en":"field"}'::jsonb),
('sky', '1F324', 'nature', 'a1_movers', false, '{"tr":"gökyüzü","az":"səma","es":"cielo","en":"sky"}'::jsonb),
('desk', '1FA91', 'school', 'pre_a1_starters', false, '{"tr":"sıra","az":"parta","es":"pupitre","en":"desk"}'::jsonb),
('classmate', '1F46B', 'school', 'a1_movers', false, '{"tr":"sınıf arkadaşı","az":"sinif yoldaşı","es":"compañero de clase","en":"classmate"}'::jsonb),
('playground', '1F3A0', 'school', 'pre_a1_starters', false, '{"tr":"oyun alanı","az":"oyun meydançası","es":"patio de recreo","en":"playground"}'::jsonb),
('library', '1F3DB', 'school', 'a1_movers', false, '{"tr":"kütüphane","az":"kitabxana","es":"biblioteca","en":"library"}'::jsonb),
('map', '1F5FA', 'school', 'a1_movers', false, '{"tr":"harita","az":"xəritə","es":"mapa","en":"map"}'::jsonb),
('page', '1F4C4', 'school', 'pre_a1_starters', false, '{"tr":"sayfa","az":"səhifə","es":"página","en":"page"}'::jsonb),
('word', '1F4AC', 'school', 'pre_a1_starters', false, '{"tr":"kelime","az":"söz","es":"palabra","en":"word"}'::jsonb),
('letter', '1F4E8', 'school', 'pre_a1_starters', false, '{"tr":"harf","az":"hərf","es":"letra","en":"letter"}'::jsonb),
('number', '1F522', 'school', 'pre_a1_starters', false, '{"tr":"sayı","az":"rəqəm","es":"número","en":"number"}'::jsonb),
('picture', '1F3BC', 'school', 'pre_a1_starters', false, '{"tr":"resim","az":"şəkil","es":"imagen","en":"picture"}'::jsonb),
('football', '26BD', 'sports', 'pre_a1_starters', false, '{"tr":"futbol","az":"futbol","es":"fútbol","en":"football"}'::jsonb),
('basketball', '1F3C0', 'sports', 'pre_a1_starters', false, '{"tr":"basketbol","az":"basketbol","es":"baloncesto","en":"basketball"}'::jsonb),
('tennis', '1F3BE', 'sports', 'pre_a1_starters', false, '{"tr":"tenis","az":"tennis","es":"tenis","en":"tennis"}'::jsonb),
('baseball', '26BE', 'sports', 'pre_a1_starters', false, '{"tr":"beyzbol","az":"beyzbol","es":"béisbol","en":"baseball"}'::jsonb),
('volleyball', '1F3D0', 'sports', 'a1_movers', false, '{"tr":"voleybol","az":"voleybol","es":"voleibol","en":"volleyball"}'::jsonb),
('hockey', '1F3D1', 'sports', 'pre_a1_starters', false, '{"tr":"hokey","az":"hokkey","es":"hockey","en":"hockey"}'::jsonb),
('badminton', '1F3F8', 'sports', 'pre_a1_starters', false, '{"tr":"badminton","az":"badminton","es":"bádminton","en":"badminton"}'::jsonb),
('swimming', '1F3CA', 'sports', 'pre_a1_starters', false, '{"tr":"yüzme","az":"üzgüçülük","es":"natación","en":"swimming"}'::jsonb),
('table tennis', '1F3D3', 'sports', 'pre_a1_starters', false, '{"tr":"masa tenisi","az":"stolüstü tennis","es":"tenis de mesa","en":"table tennis"}'::jsonb),
('rugby', '1F3C9', 'sports', 'a2_flyers', false, '{"tr":"ragbi","az":"reqbi","es":"rugby","en":"rugby"}'::jsonb),
('motorbike', '1F3CD', 'transport', 'pre_a1_starters', false, '{"tr":"motosiklet","az":"motosikl","es":"motocicleta","en":"motorbike"}'::jsonb),
('ticket', '1F3AB', 'transport', 'a1_movers', false, '{"tr":"bilet","az":"bilet","es":"billete","en":"ticket"}'::jsonb),
('station', '1F689', 'transport', 'a1_movers', false, '{"tr":"istasyon","az":"stansiya","es":"estación","en":"station"}'::jsonb),
('airport', '1F6EC', 'transport', 'a1_movers', false, '{"tr":"havalimanı","az":"hava limanı","es":"aeropuerto","en":"airport"}'::jsonb),
('street', '1F6E3', 'transport', 'pre_a1_starters', false, '{"tr":"sokak","az":"küçə","es":"calle","en":"street"}'::jsonb),
('road', '1F6E3', 'transport', 'a1_movers', false, '{"tr":"yol","az":"yol","es":"camino","en":"road"}'::jsonb),
('bridge', '1F309', 'transport', 'a2_flyers', false, '{"tr":"köprü","az":"körpü","es":"puente","en":"bridge"}'::jsonb),
('ship', '1F6A2', 'transport', 'a1_movers', false, '{"tr":"gemi","az":"gəmi","es":"barco","en":"ship"}'::jsonb),
('truck', '1F69A', 'transport', 'pre_a1_starters', false, '{"tr":"kamyon","az":"yük maşını","es":"camión","en":"truck"}'::jsonb),
('scooter', '1F6F4', 'transport', 'a1_movers', false, '{"tr":"skuter","az":"skuter","es":"patinete","en":"scooter"}'::jsonb),
('board game', '1F3B2', 'toys', 'a1_movers', false, '{"tr":"kutu oyunu","az":"stolüstü oyun","es":"juego de mesa","en":"board game"}'::jsonb),
('skipping rope', '1F9FF', 'toys', 'a1_movers', false, '{"tr":"atlama ipi","az":"atlama ipi","es":"cuerda para saltar","en":"skipping rope"}'::jsonb),
('roller skates', '1F6FC', 'toys', 'a1_movers', false, '{"tr":"paten","az":"rolik","es":"patines","en":"roller skates"}'::jsonb),
('skateboard', '1F6FC', 'toys', 'a1_movers', false, '{"tr":"kaykay","az":"skeytbord","es":"monopatín","en":"skateboard"}'::jsonb),
('guitar', '1F3B8', 'toys', 'pre_a1_starters', false, '{"tr":"gitar","az":"gitara","es":"guitarra","en":"guitar"}'::jsonb),
('polite', '1F91D', 'values', 'a2_flyers', true, '{"tr":"kibar","az":"nəzakətli","es":"educado","en":"polite"}'::jsonb),
('brave', '1F9B8', 'values', 'a1_movers', true, '{"tr":"cesur","az":"cəsur","es":"valiente","en":"brave"}'::jsonb),
('fair', '2696', 'values', 'a2_flyers', true, '{"tr":"adil","az":"ədalətli","es":"justo","en":"fair"}'::jsonb),
('patient', '1F553', 'values', 'a2_flyers', true, '{"tr":"sabırlı","az":"səbirli","es":"paciente","en":"patient"}'::jsonb),
('good', '1F44D', 'values', 'pre_a1_starters', true, '{"tr":"iyi","az":"yaxşı","es":"bueno","en":"good"}'::jsonb),
('pig', '1F437', 'animals', 'pre_a1_starters', false, '{"tr":"domuz","az":"donuz","es":"cerdo","en":"pig"}'::jsonb),
('donkey', '1FACF', 'animals', 'a1_movers', false, '{"tr":"eşek","az":"ulaq","es":"burro","en":"donkey"}'::jsonb),
('camel', '1F42A', 'animals', 'a2_flyers', false, '{"tr":"deve","az":"dəvə","es":"camello","en":"camel"}'::jsonb),
('kangaroo', '1F998', 'animals', 'a1_movers', false, '{"tr":"kanguru","az":"kenquru","es":"canguro","en":"kangaroo"}'::jsonb),
('penguin', '1F427', 'animals', 'a1_movers', false, '{"tr":"penguen","az":"pinqvin","es":"pingüino","en":"penguin"}'::jsonb),
('dolphin', '1F42C', 'animals', 'a1_movers', false, '{"tr":"yunus","az":"yunus","es":"delfín","en":"dolphin"}'::jsonb),
('whale', '1F433', 'animals', 'a1_movers', false, '{"tr":"balina","az":"balina","es":"ballena","en":"whale"}'::jsonb),
('shark', '1F988', 'animals', 'a1_movers', false, '{"tr":"köpek balığı","az":"köpək balığı","es":"tiburón","en":"shark"}'::jsonb),
('octopus', '1F419', 'animals', 'a2_flyers', false, '{"tr":"ahtapot","az":"səkkizayaqlı","es":"pulpo","en":"octopus"}'::jsonb),
('insect', '1F41B', 'animals', 'a2_flyers', false, '{"tr":"böcek","az":"həşərat","es":"insecto","en":"insect"}'::jsonb),
('fly', '1FAB0', 'animals', 'a2_flyers', false, '{"tr":"sinek","az":"milçək","es":"mosca","en":"fly"}'::jsonb),
('butterfly', '1F98B', 'animals', 'a1_movers', false, '{"tr":"kelebek","az":"kəpənək","es":"mariposa","en":"butterfly"}'::jsonb),
('swan', '1F9A2', 'animals', 'a2_flyers', false, '{"tr":"kuğu","az":"qu quşu","es":"cisne","en":"swan"}'::jsonb),
('parrot', '1F99C', 'animals', 'a1_movers', false, '{"tr":"papağan","az":"tutuquşu","es":"loro","en":"parrot"}'::jsonb),
('dinosaur', '1F996', 'animals', 'a2_flyers', false, '{"tr":"dinozor","az":"dinozavr","es":"dinosaurio","en":"dinosaur"}'::jsonb),
('meat', '1F356', 'food', 'pre_a1_starters', false, '{"tr":"et","az":"ət","es":"carne","en":"meat"}'::jsonb),
('fruit', '1F34E', 'food', 'pre_a1_starters', false, '{"tr":"meyve","az":"meyvə","es":"fruta","en":"fruit"}'::jsonb),
('grape', '1F347', 'food', 'pre_a1_starters', false, '{"tr":"üzüm","az":"üzüm","es":"uva","en":"grape"}'::jsonb),
('lemon', '1F34B', 'food', 'pre_a1_starters', false, '{"tr":"limon","az":"limon","es":"limón","en":"lemon"}'::jsonb),
('mango', '1F96D', 'food', 'a1_movers', false, '{"tr":"mango","az":"manqo","es":"mango","en":"mango"}'::jsonb),
('pear', '1F350', 'food', 'pre_a1_starters', false, '{"tr":"armut","az":"armud","es":"pera","en":"pear"}'::jsonb),
('pineapple', '1F34D', 'food', 'pre_a1_starters', false, '{"tr":"ananas","az":"ananas","es":"piña","en":"pineapple"}'::jsonb),
('coconut', '1F965', 'food', 'pre_a1_starters', false, '{"tr":"hindistan cevizi","az":"hindistan cəvizi","es":"coco","en":"coconut"}'::jsonb),
('watermelon', '1F349', 'food', 'pre_a1_starters', false, '{"tr":"karpuz","az":"qarpız","es":"sandía","en":"watermelon"}'::jsonb),
('pasta', '1F35D', 'food', 'a1_movers', false, '{"tr":"makarna","az":"makaron","es":"pasta","en":"pasta"}'::jsonb),
('sandwich', '1F96A', 'food', 'pre_a1_starters', false, '{"tr":"sandviç","az":"sendviç","es":"sándwich","en":"sandwich"}'::jsonb),
('chips', '1F35F', 'food', 'pre_a1_starters', false, '{"tr":"patates kızartması","az":"qızardılmış kartof","es":"papas fritas","en":"chips"}'::jsonb),
('biscuit', '1F36A', 'food', 'a1_movers', false, '{"tr":"bisküvi","az":"biskvit","es":"galleta","en":"biscuit"}'::jsonb),
('sugar', '1F9C2', 'food', 'a2_flyers', false, '{"tr":"şeker","az":"şəkər","es":"azúcar","en":"sugar"}'::jsonb),
('salt', '1F9C2', 'food', 'a2_flyers', false, '{"tr":"tuz","az":"duz","es":"sal","en":"salt"}'::jsonb),
('thumb', '1F44D', 'body', 'a2_flyers', false, '{"tr":"başparmak","az":"baş barmaq","es":"pulgar","en":"thumb"}'::jsonb),
('bone', '1F9B4', 'body', 'a2_flyers', false, '{"tr":"kemik","az":"sümük","es":"hueso","en":"bone"}'::jsonb),
('blood', '1FA78', 'body', 'a2_flyers', false, '{"tr":"kan","az":"qan","es":"sangre","en":"blood"}'::jsonb),
('brain', '1F9E0', 'body', 'a2_flyers', false, '{"tr":"beyin","az":"beyin","es":"cerebro","en":"brain"}'::jsonb),
('heart', '2764', 'body', 'a1_movers', false, '{"tr":"kalp","az":"ürək","es":"corazón","en":"heart"}'::jsonb),
('skin', '1F9D1', 'body', 'a2_flyers', false, '{"tr":"deri","az":"dəri","es":"piel","en":"skin"}'::jsonb),
('beard', '1F9D4', 'body', 'a1_movers', false, '{"tr":"sakal","az":"saqqal","es":"barba","en":"beard"}'::jsonb),
('moustache', '1F9D4', 'body', 'a1_movers', false, '{"tr":"bıyık","az":"bığ","es":"bigote","en":"moustache"}'::jsonb),
('tail', '1F415', 'body', 'pre_a1_starters', false, '{"tr":"kuyruk","az":"quyruq","es":"cola","en":"tail"}'::jsonb),
('wing', '1F426', 'body', 'a1_movers', false, '{"tr":"kanat","az":"qanad","es":"ala","en":"wing"}'::jsonb),
('uniform', '1F9D1', 'clothes', 'a2_flyers', false, '{"tr":"üniforma","az":"forma","es":"uniforme","en":"uniform"}'::jsonb),
('trainers', '1F45F', 'clothes', 'a1_movers', false, '{"tr":"spor ayakkabı","az":"idman ayaqqabısı","es":"zapatillas","en":"trainers"}'::jsonb),
('raincoat', '1F9E5', 'clothes', 'a1_movers', false, '{"tr":"yağmurluk","az":"yağmurluq","es":"impermeable","en":"raincoat"}'::jsonb),
('sunglasses', '1F576', 'clothes', 'a1_movers', false, '{"tr":"güneş gözlüğü","az":"günəş eynəyi","es":"gafas de sol","en":"sunglasses"}'::jsonb),
('pocket', '1F456', 'clothes', 'a2_flyers', false, '{"tr":"cep","az":"cib","es":"bolsillo","en":"pocket"}'::jsonb),
('button', '1F518', 'clothes', 'a2_flyers', false, '{"tr":"düğme","az":"düymə","es":"botón","en":"button"}'::jsonb),
('helmet', '1FA96', 'clothes', 'a1_movers', false, '{"tr":"kask","az":"dəbilqə","es":"casco","en":"helmet"}'::jsonb),
('watch', '231A', 'clothes', 'pre_a1_starters', false, '{"tr":"saat (kol)","az":"qol saatı","es":"reloj","en":"watch"}'::jsonb),
('ring', '1F48D', 'clothes', 'a2_flyers', false, '{"tr":"yüzük","az":"üzük","es":"anillo","en":"ring"}'::jsonb),
('necklace', '1F4FF', 'clothes', 'a2_flyers', false, '{"tr":"kolye","az":"boyunbağı","es":"collar","en":"necklace"}'::jsonb),
('weather', '1F324', 'nature', 'a1_movers', false, '{"tr":"hava","az":"hava","es":"clima","en":"weather"}'::jsonb),
('storm', '1F329', 'nature', 'a2_flyers', false, '{"tr":"fırtına","az":"fırtına","es":"tormenta","en":"storm"}'::jsonb),
('fog', '1F32B', 'nature', 'a2_flyers', false, '{"tr":"sis","az":"duman","es":"niebla","en":"fog"}'::jsonb),
('ice', '1F9CA', 'nature', 'a1_movers', false, '{"tr":"buz","az":"buz","es":"hielo","en":"ice"}'::jsonb),
('fire', '1F525', 'nature', 'a1_movers', false, '{"tr":"ateş","az":"od","es":"fuego","en":"fire"}'::jsonb),
('forest', '1F332', 'nature', 'a1_movers', false, '{"tr":"orman","az":"meşə","es":"bosque","en":"forest"}'::jsonb),
('waterfall', '1F30A', 'nature', 'a2_flyers', false, '{"tr":"şelale","az":"şəlalə","es":"cascada","en":"waterfall"}'::jsonb),
('leaf', '1F342', 'nature', 'a1_movers', false, '{"tr":"yaprak","az":"yarpaq","es":"hoja","en":"leaf"}'::jsonb),
('ground', '1F3D5', 'nature', 'a2_flyers', false, '{"tr":"yer","az":"yer","es":"suelo","en":"ground"}'::jsonb),
('space', '1F30C', 'nature', 'a2_flyers', false, '{"tr":"uzay","az":"kosmos","es":"espacio","en":"space"}'::jsonb),
('planet', '1FA90', 'nature', 'a2_flyers', false, '{"tr":"gezegen","az":"planet","es":"planeta","en":"planet"}'::jsonb),
('earth', '1F30D', 'nature', 'a2_flyers', false, '{"tr":"dünya","az":"dünya","es":"Tierra","en":"earth"}'::jsonb),
('lake', '1F3DE', 'nature', 'a1_movers', false, '{"tr":"göl","az":"göl","es":"lago","en":"lake"}'::jsonb),
('hill', '1F3D4', 'nature', 'a2_flyers', false, '{"tr":"tepe","az":"təpə","es":"colina","en":"hill"}'::jsonb),
('wave', '1F30A', 'nature', 'a1_movers', false, '{"tr":"dalga","az":"dalğa","es":"ola","en":"wave"}'::jsonb),
('backpack', '1F392', 'school', 'a1_movers', false, '{"tr":"sırt çantası","az":"kürək çantası","es":"mochila","en":"backpack"}'::jsonb),
('glue', '1F4A7', 'school', 'a2_flyers', false, '{"tr":"yapıştırıcı","az":"yapışqan","es":"pegamento","en":"glue"}'::jsonb),
('scissors', '2702', 'school', 'a2_flyers', false, '{"tr":"makas","az":"qayçı","es":"tijeras","en":"scissors"}'::jsonb),
('notebook', '1F4D3', 'school', 'pre_a1_starters', false, '{"tr":"defter","az":"dəftər","es":"cuaderno","en":"notebook"}'::jsonb),
('paper', '1F4C4', 'school', 'pre_a1_starters', false, '{"tr":"kağıt","az":"kağız","es":"papel","en":"paper"}'::jsonb),
('exam', '1F4DD', 'school', 'a2_flyers', false, '{"tr":"sınav","az":"imtahan","es":"examen","en":"exam"}'::jsonb),
('homework', '1F4DA', 'school', 'a1_movers', false, '{"tr":"ödev","az":"ev tapşırığı","es":"tarea","en":"homework"}'::jsonb),
('classroom', '1F3EB', 'school', 'pre_a1_starters', false, '{"tr":"sınıf","az":"sinif","es":"aula","en":"classroom"}'::jsonb),
('dictionary', '1F4D5', 'school', 'a2_flyers', false, '{"tr":"sözlük","az":"lüğət","es":"diccionario","en":"dictionary"}'::jsonb),
('internet', '1F310', 'school', 'a1_movers', false, '{"tr":"internet","az":"internet","es":"internet","en":"internet"}'::jsonb),
('website', '1F4BB', 'school', 'a1_movers', false, '{"tr":"web sitesi","az":"veb sayt","es":"sitio web","en":"website"}'::jsonb),
('keyboard', '2328', 'school', 'a1_movers', false, '{"tr":"klavye","az":"klaviatura","es":"teclado","en":"keyboard"}'::jsonb),
('screen', '1F5A5', 'school', 'a1_movers', false, '{"tr":"ekran","az":"ekran","es":"pantalla","en":"screen"}'::jsonb),
('text', '1F4AC', 'school', 'a1_movers', false, '{"tr":"metin","az":"mətn","es":"texto","en":"text"}'::jsonb),
('tablet', '1F4F1', 'school', 'a1_movers', false, '{"tr":"tablet","az":"planşet","es":"tableta","en":"tablet"}'::jsonb),
('apartment', '1F3E2', 'home', 'pre_a1_starters', false, '{"tr":"apartman","az":"bina evi","es":"apartamento","en":"apartment"}'::jsonb),
('balcony', '1F3D8', 'home', 'a1_movers', false, '{"tr":"balkon","az":"balkon","es":"balcón","en":"balcony"}'::jsonb),
('basement', '1F6AA', 'home', 'a1_movers', false, '{"tr":"bodrum","az":"zirzəmi","es":"sótano","en":"basement"}'::jsonb),
('blanket', '1F6CF', 'home', 'a1_movers', false, '{"tr":"battaniye","az":"yorğan","es":"manta","en":"blanket"}'::jsonb),
('toothbrush', '1FA95', 'home', 'a1_movers', false, '{"tr":"diş fırçası","az":"diş fırçası","es":"cepillo de dientes","en":"toothbrush"}'::jsonb),
('pillow', '1F6CF', 'home', 'a1_movers', false, '{"tr":"yastık","az":"yastıq","es":"almohada","en":"pillow"}'::jsonb),
('cupboard', '1F6AA', 'home', 'pre_a1_starters', false, '{"tr":"dolap","az":"dolab","es":"armario","en":"cupboard"}'::jsonb),
('drawer', '1F6AA', 'home', 'a1_movers', false, '{"tr":"çekmece","az":"çəkməcə","es":"cajón","en":"drawer"}'::jsonb),
('fridge', '1F9CA', 'home', 'a1_movers', false, '{"tr":"buzdolabı","az":"soyuducu","es":"nevera","en":"fridge"}'::jsonb),
('cooker', '1F373', 'home', 'a1_movers', false, '{"tr":"ocak","az":"qaz peçi","es":"cocina","en":"cooker"}'::jsonb),
('bowl', '1F963', 'home', 'a1_movers', false, '{"tr":"kase","az":"kasa","es":"cuenco","en":"bowl"}'::jsonb),
('plate', '1F37D', 'home', 'pre_a1_starters', false, '{"tr":"tabak","az":"boşqab","es":"plato","en":"plate"}'::jsonb),
('cup', '1F375', 'home', 'pre_a1_starters', false, '{"tr":"kupa","az":"fincan","es":"taza","en":"cup"}'::jsonb),
('glass', '1F943', 'home', 'pre_a1_starters', false, '{"tr":"bardak","az":"stəkan","es":"vaso","en":"glass"}'::jsonb),
('fork', '1F374', 'home', 'a1_movers', false, '{"tr":"çatal","az":"çəngəl","es":"tenedor","en":"fork"}'::jsonb),
('friendly', '1F91D', 'values', 'a1_movers', true, '{"tr":"arkadaş canlısı","az":"mehriban","es":"amigable","en":"friendly"}'::jsonb),
('helpful', '1F44D', 'values', 'a1_movers', true, '{"tr":"yardımsever","az":"köməkcil","es":"servicial","en":"helpful"}'::jsonb),
('generous', '1F381', 'values', 'a2_flyers', true, '{"tr":"cömert","az":"səxavətli","es":"generoso","en":"generous"}'::jsonb),
('calm', '1F60C', 'values', 'a2_flyers', true, '{"tr":"sakin","az":"sakit","es":"tranquilo","en":"calm"}'::jsonb),
('peaceful', '262E', 'values', 'a2_flyers', true, '{"tr":"huzurlu","az":"hüzurlu","es":"pacífico","en":"peaceful"}'::jsonb),
('doctor', '1FA7A', 'jobs', 'pre_a1_starters', false, '{"tr":"doktor","az":"həkim","es":"médico","en":"doctor"}'::jsonb),
('police', '1F46E', 'jobs', 'pre_a1_starters', false, '{"tr":"polis","az":"polis","es":"policía","en":"police"}'::jsonb),
('farmer', '1F33E', 'jobs', 'a1_movers', false, '{"tr":"çiftçi","az":"fermer","es":"granjero","en":"farmer"}'::jsonb),
('pilot', '2708', 'jobs', 'a2_flyers', false, '{"tr":"pilot","az":"pilot","es":"piloto","en":"pilot"}'::jsonb),
('singer', '1F3A4', 'jobs', 'a1_movers', false, '{"tr":"şarkıcı","az":"müğənni","es":"cantante","en":"singer"}'::jsonb),
('actor', '1F3AD', 'jobs', 'a2_flyers', false, '{"tr":"oyuncu","az":"aktyor","es":"actor","en":"actor"}'::jsonb),
('dentist', '1F9B7', 'jobs', 'a2_flyers', false, '{"tr":"diş hekimi","az":"diş həkimi","es":"dentista","en":"dentist"}'::jsonb),
('cook', '1F373', 'jobs', 'a1_movers', false, '{"tr":"aşçı","az":"aşpaz","es":"cocinero","en":"cook"}'::jsonb),
('driver', '1F697', 'jobs', 'a1_movers', false, '{"tr":"sürücü","az":"sürücü","es":"conductor","en":"driver"}'::jsonb),
('clown', '1F921', 'jobs', 'a1_movers', false, '{"tr":"palyaço","az":"təlxək","es":"payaso","en":"clown"}'::jsonb),
('mechanic', '1F527', 'jobs', 'a2_flyers', false, '{"tr":"tamirci","az":"mexanik","es":"mecánico","en":"mechanic"}'::jsonb),
('nurse', '1FA7A', 'jobs', 'a1_movers', false, '{"tr":"hemşire","az":"tibb bacısı","es":"enfermera","en":"nurse"}'::jsonb),
('pirate', '1F3F4', 'jobs', 'a1_movers', false, '{"tr":"korsan","az":"pirat","es":"pirata","en":"pirate"}'::jsonb),
('alien', '1F47D', 'jobs', 'pre_a1_starters', false, '{"tr":"uzaylı","az":"yadplanetli","es":"extraterrestre","en":"alien"}'::jsonb),
('king', '1F451', 'jobs', 'a2_flyers', false, '{"tr":"kral","az":"kral","es":"rey","en":"king"}'::jsonb),
('queen', '1F451', 'jobs', 'a2_flyers', false, '{"tr":"kraliçe","az":"kraliça","es":"reina","en":"queen"}'::jsonb),
('run', '1F3C3', 'actions', 'pre_a1_starters', false, '{"tr":"koşmak","az":"qaçmaq","es":"correr","en":"run"}'::jsonb),
('walk', '1F6B6', 'actions', 'pre_a1_starters', false, '{"tr":"yürümek","az":"gəzmək","es":"caminar","en":"walk"}'::jsonb),
('jump', '1F998', 'actions', 'pre_a1_starters', false, '{"tr":"zıplamak","az":"tullanmaq","es":"saltar","en":"jump"}'::jsonb),
('sleep', '1F4A4', 'actions', 'pre_a1_starters', false, '{"tr":"uyumak","az":"yatmaq","es":"dormir","en":"sleep"}'::jsonb),
('eat', '1F37D', 'actions', 'pre_a1_starters', false, '{"tr":"yemek yemek","az":"yemək yemək","es":"comer","en":"eat"}'::jsonb),
('drink', '1F964', 'actions', 'pre_a1_starters', false, '{"tr":"içmek","az":"içmək","es":"beber","en":"drink"}'::jsonb),
('read', '1F4D6', 'actions', 'pre_a1_starters', false, '{"tr":"okumak","az":"oxumaq","es":"leer","en":"read"}'::jsonb),
('write', '270D', 'actions', 'pre_a1_starters', false, '{"tr":"yazmak","az":"yazmaq","es":"escribir","en":"write"}'::jsonb),
('draw', '1F3A8', 'actions', 'pre_a1_starters', false, '{"tr":"çizmek","az":"rəsm çəkmək","es":"dibujar","en":"draw"}'::jsonb),
('sing', '1F3A4', 'actions', 'pre_a1_starters', false, '{"tr":"şarkı söylemek","az":"mahnı oxumaq","es":"cantar","en":"sing"}'::jsonb),
('dance', '1F483', 'actions', 'a1_movers', false, '{"tr":"dans etmek","az":"rəqs etmək","es":"bailar","en":"dance"}'::jsonb),
('play', '1F3AE', 'actions', 'pre_a1_starters', false, '{"tr":"oynamak","az":"oynamaq","es":"jugar","en":"play"}'::jsonb),
('listen', '1F3A7', 'actions', 'pre_a1_starters', false, '{"tr":"dinlemek","az":"dinləmək","es":"escuchar","en":"listen"}'::jsonb),
('look', '1F440', 'actions', 'pre_a1_starters', false, '{"tr":"bakmak","az":"baxmaq","es":"mirar","en":"look"}'::jsonb),
('watch', '1F4FA', 'actions', 'pre_a1_starters', false, '{"tr":"izlemek","az":"izləmək","es":"ver","en":"watch"}'::jsonb),
('talk', '1F4E3', 'actions', 'pre_a1_starters', false, '{"tr":"konuşmak","az":"danışmaq","es":"hablar","en":"talk"}'::jsonb),
('catch', '1F93E', 'actions', 'pre_a1_starters', false, '{"tr":"yakalamak","az":"tutmaq","es":"atrapar","en":"catch"}'::jsonb),
('throw', '1F3D0', 'actions', 'pre_a1_starters', false, '{"tr":"atmak","az":"atmaq","es":"lanzar","en":"throw"}'::jsonb),
('ride', '1F6B2', 'actions', 'pre_a1_starters', false, '{"tr":"sürmek (bisiklet)","az":"sürmək","es":"montar","en":"ride"}'::jsonb),
('drive', '1F697', 'actions', 'a1_movers', false, '{"tr":"sürmek (araba)","az":"maşın sürmək","es":"conducir","en":"drive"}'::jsonb),
('fly', '2708', 'actions', 'pre_a1_starters', false, '{"tr":"uçmak","az":"uçmaq","es":"volar","en":"fly"}'::jsonb),
('climb', '1F9D7', 'actions', 'a1_movers', false, '{"tr":"tırmanmak","az":"dırmaşmaq","es":"escalar","en":"climb"}'::jsonb),
('cry', '1F622', 'actions', 'a1_movers', false, '{"tr":"ağlamak","az":"ağlamaq","es":"llorar","en":"cry"}'::jsonb),
('laugh', '1F602', 'actions', 'a1_movers', false, '{"tr":"gülmek","az":"gülmək","es":"reír","en":"laugh"}'::jsonb),
('smile', '1F642', 'actions', 'pre_a1_starters', false, '{"tr":"gülümsemek","az":"gülümsəmək","es":"sonreír","en":"smile"}'::jsonb),
('open', '1F5DD', 'actions', 'pre_a1_starters', false, '{"tr":"açmak","az":"açmaq","es":"abrir","en":"open"}'::jsonb),
('close', '1F512', 'actions', 'pre_a1_starters', false, '{"tr":"kapatmak","az":"bağlamaq","es":"cerrar","en":"close"}'::jsonb),
('stand', '1F9CD', 'actions', 'pre_a1_starters', false, '{"tr":"ayakta durmak","az":"ayaq üstə durmaq","es":"estar de pie","en":"stand"}'::jsonb),
('sit', '1FA91', 'actions', 'pre_a1_starters', false, '{"tr":"oturmak","az":"oturmaq","es":"sentarse","en":"sit"}'::jsonb),
('wash', '1F9FC', 'actions', 'a1_movers', false, '{"tr":"yıkamak","az":"yumaq","es":"lavar","en":"wash"}'::jsonb),
('big', '1F418', 'adjectives', 'pre_a1_starters', false, '{"tr":"büyük","az":"böyük","es":"grande","en":"big"}'::jsonb),
('small', '1F42D', 'adjectives', 'pre_a1_starters', false, '{"tr":"küçük","az":"kiçik","es":"pequeño","en":"small"}'::jsonb),
('tall', '1F992', 'adjectives', 'a1_movers', false, '{"tr":"uzun (boy)","az":"uzun","es":"alto","en":"tall"}'::jsonb),
('short', '1F4CF', 'adjectives', 'pre_a1_starters', false, '{"tr":"kısa","az":"qısa","es":"corto","en":"short"}'::jsonb),
('long', '1F40D', 'adjectives', 'pre_a1_starters', false, '{"tr":"uzun","az":"uzun","es":"largo","en":"long"}'::jsonb),
('fast', '1F406', 'adjectives', 'a1_movers', false, '{"tr":"hızlı","az":"sürətli","es":"rápido","en":"fast"}'::jsonb),
('slow', '1F40C', 'adjectives', 'a1_movers', false, '{"tr":"yavaş","az":"yavaş","es":"lento","en":"slow"}'::jsonb),
('hot', '1F525', 'adjectives', 'a1_movers', false, '{"tr":"sıcak","az":"isti","es":"caliente","en":"hot"}'::jsonb),
('cold', '1F9CA', 'adjectives', 'a1_movers', false, '{"tr":"soğuk","az":"soyuq","es":"frío","en":"cold"}'::jsonb),
('hungry', '1F924', 'adjectives', 'a2_flyers', false, '{"tr":"aç","az":"ac","es":"hambriento","en":"hungry"}'::jsonb),
('thirsty', '1F964', 'adjectives', 'a2_flyers', false, '{"tr":"susamış","az":"susuz","es":"sediento","en":"thirsty"}'::jsonb),
('tired', '1F62B', 'adjectives', 'a1_movers', false, '{"tr":"yorgun","az":"yorğun","es":"cansado","en":"tired"}'::jsonb),
('angry', '1F621', 'adjectives', 'pre_a1_starters', false, '{"tr":"kızgın","az":"qəzəbli","es":"enojado","en":"angry"}'::jsonb),
('sad', '1F622', 'adjectives', 'pre_a1_starters', false, '{"tr":"üzgün","az":"kədərli","es":"triste","en":"sad"}'::jsonb),
('beautiful', '1F339', 'adjectives', 'pre_a1_starters', false, '{"tr":"güzel","az":"gözəl","es":"hermoso","en":"beautiful"}'::jsonb),
('ugly', '1F479', 'adjectives', 'a1_movers', false, '{"tr":"çirkin","az":"çirkin","es":"feo","en":"ugly"}'::jsonb),
('dirty', '1F4A9', 'adjectives', 'a1_movers', false, '{"tr":"kirli","az":"çirkli","es":"sucio","en":"dirty"}'::jsonb),
('old', '1F474', 'adjectives', 'pre_a1_starters', false, '{"tr":"eski / yaşlı","az":"köhnə / qoca","es":"viejo","en":"old"}'::jsonb),
('new', '1F195', 'adjectives', 'pre_a1_starters', false, '{"tr":"yeni","az":"yeni","es":"nuevo","en":"new"}'::jsonb),
('young', '1F476', 'adjectives', 'pre_a1_starters', false, '{"tr":"genç","az":"gənc","es":"joven","en":"young"}'::jsonb),
('loud', '1F50A', 'adjectives', 'a1_movers', false, '{"tr":"gürültülü","az":"səs-küylü","es":"ruidoso","en":"loud"}'::jsonb),
('quiet', '1F92B', 'adjectives', 'a1_movers', false, '{"tr":"sessiz","az":"səssiz","es":"silencioso","en":"quiet"}'::jsonb),
('funny', '1F923', 'adjectives', 'pre_a1_starters', false, '{"tr":"komik","az":"gülməli","es":"divertido","en":"funny"}'::jsonb),
('bad', '1F44E', 'adjectives', 'pre_a1_starters', false, '{"tr":"kötü","az":"pis","es":"malo","en":"bad"}'::jsonb),
('smart', '1F9E0', 'adjectives', 'a2_flyers', false, '{"tr":"zeki","az":"ağıllı","es":"inteligente","en":"smart"}'::jsonb),
('day', '2600', 'time', 'pre_a1_starters', false, '{"tr":"gün","az":"gün","es":"día","en":"day"}'::jsonb),
('night', '1F319', 'time', 'pre_a1_starters', false, '{"tr":"gece","az":"gecə","es":"noche","en":"night"}'::jsonb),
('morning', '1F304', 'time', 'pre_a1_starters', false, '{"tr":"sabah","az":"səhər","es":"mañana","en":"morning"}'::jsonb),
('afternoon', '1F31E', 'time', 'pre_a1_starters', false, '{"tr":"öğleden sonra","az":"günorta","es":"tarde","en":"afternoon"}'::jsonb),
('evening', '1F307', 'time', 'pre_a1_starters', false, '{"tr":"akşam","az":"axşam","es":"noche","en":"evening"}'::jsonb),
('today', '1F4C5', 'time', 'pre_a1_starters', false, '{"tr":"bugün","az":"bugün","es":"hoy","en":"today"}'::jsonb),
('tomorrow', '1F4C6', 'time', 'a2_flyers', false, '{"tr":"yarın","az":"sabah","es":"mañana","en":"tomorrow"}'::jsonb),
('yesterday', '1F4C4', 'time', 'a2_flyers', false, '{"tr":"dün","az":"dünən","es":"ayer","en":"yesterday"}'::jsonb),
('week', '1F4D1', 'time', 'a1_movers', false, '{"tr":"hafta","az":"həftə","es":"semana","en":"week"}'::jsonb),
('month', '1F4C5', 'time', 'a2_flyers', false, '{"tr":"ay","az":"ay","es":"mes","en":"month"}'::jsonb),
('year', '1F389', 'time', 'a1_movers', false, '{"tr":"yıl","az":"il","es":"año","en":"year"}'::jsonb),
('monday', '1F4C5', 'time', 'pre_a1_starters', false, '{"tr":"pazartesi","az":"bazar ertəsi","es":"lunes","en":"monday"}'::jsonb),
('friday', '1F4C5', 'time', 'pre_a1_starters', false, '{"tr":"cuma","az":"cümə","es":"viernes","en":"friday"}'::jsonb),
('sunday', '1F4C5', 'time', 'pre_a1_starters', false, '{"tr":"pazar","az":"bazar","es":"domingo","en":"sunday"}'::jsonb),
('hospital', '1F3E5', 'places', 'a1_movers', false, '{"tr":"hastane","az":"xəstəxana","es":"hospital","en":"hospital"}'::jsonb),
('bank', '1F3E6', 'places', 'a1_movers', false, '{"tr":"banka","az":"bank","es":"banco","en":"bank"}'::jsonb),
('park', '1F3DE', 'places', 'pre_a1_starters', false, '{"tr":"park","az":"park","es":"parque","en":"park"}'::jsonb),
('zoo', '1F993', 'places', 'pre_a1_starters', false, '{"tr":"hayvanat bahçesi","az":"zoopark","es":"zoológico","en":"zoo"}'::jsonb),
('cinema', '1F3A6', 'places', 'a1_movers', false, '{"tr":"sinema","az":"kino","es":"cine","en":"cinema"}'::jsonb),
('supermarket', '1F6D2', 'places', 'a1_movers', false, '{"tr":"süpermarket","az":"supermarket","es":"supermercado","en":"supermarket"}'::jsonb),
('market', '1F34E', 'places', 'a1_movers', false, '{"tr":"pazar","az":"bazar","es":"mercado","en":"market"}'::jsonb),
('town', '1F3D9', 'places', 'a1_movers', false, '{"tr":"kasaba","az":"qəsəbə","es":"pueblo","en":"town"}'::jsonb),
('city', '1F3D9', 'places', 'a1_movers', false, '{"tr":"şehir","az":"şəhər","es":"ciudad","en":"city"}'::jsonb),
('village', '1F3E1', 'places', 'a2_flyers', false, '{"tr":"köy","az":"kənd","es":"pueblo","en":"village"}'::jsonb),
('loyal', '1F91D', 'values', 'a2_flyers', true, '{"tr":"sadık","az":"sadiq","es":"leal","en":"loyal"}'::jsonb),
('gentle', '1F343', 'values', 'a2_flyers', true, '{"tr":"nazik / yumuşak","az":"mülayim","es":"suave","en":"gentle"}'::jsonb),
('responsible', '1F4BC', 'values', 'a2_flyers', true, '{"tr":"sorumlu","az":"məsuliyyətli","es":"responsable","en":"responsible"}'::jsonb),
('forgiving', '1F91D', 'values', 'a2_flyers', true, '{"tr":"affedici","az":"bağışlayan","es":"indulgente","en":"forgiving"}'::jsonb),
('hard-working', '1F4AA', 'values', 'a2_flyers', true, '{"tr":"çalışkan","az":"çalışqan","es":"trabajador","en":"hard-working"}'::jsonb),
('mother', '1F469', 'family', 'pre_a1_starters', false, '{"tr":"anne","az":"ana","es":"madre","en":"mother"}'::jsonb),
('father', '1F468', 'family', 'pre_a1_starters', false, '{"tr":"baba","az":"ata","es":"padre","en":"father"}'::jsonb),
('brother', '1F466', 'family', 'pre_a1_starters', false, '{"tr":"erkek kardeş","az":"qardaş","es":"hermano","en":"brother"}'::jsonb),
('sister', '1F467', 'family', 'pre_a1_starters', false, '{"tr":"kız kardeş","az":"bacı","es":"hermana","en":"sister"}'::jsonb),
('grandfather', '1F474', 'family', 'pre_a1_starters', false, '{"tr":"büyükbaba","az":"baba","es":"abuelo","en":"grandfather"}'::jsonb),
('grandmother', '1F475', 'family', 'pre_a1_starters', false, '{"tr":"büyükanne","az":"nənə","es":"abuela","en":"grandmother"}'::jsonb),
('baby', '1F476', 'family', 'pre_a1_starters', false, '{"tr":"bebek","az":"körpə","es":"bebé","en":"baby"}'::jsonb),
('cousin', '1F9D2', 'family', 'pre_a1_starters', false, '{"tr":"kuzen","az":"əmioğlu/dayıoğlu","es":"primo","en":"cousin"}'::jsonb),
('uncle', '1F468', 'family', 'a1_movers', false, '{"tr":"amca / dayı","az":"əmi / dayı","es":"tío","en":"uncle"}'::jsonb),
('aunt', '1F469', 'family', 'a1_movers', false, '{"tr":"hala / teyze","az":"bibi / xala","es":"tía","en":"aunt"}'::jsonb),
('cheek', '1F60A', 'body', 'a2_flyers', false, '{"tr":"yanak","az":"yanaq","es":"mejilla","en":"cheek"}'::jsonb),
('chin', '1F9D4', 'body', 'a2_flyers', false, '{"tr":"çene","az":"çənə","es":"barbilla","en":"chin"}'::jsonb),
('chest', '1F9D1', 'body', 'a2_flyers', false, '{"tr":"göğüs","az":"sinə","es":"pecho","en":"chest"}'::jsonb),
('lip', '1F444', 'body', 'a2_flyers', false, '{"tr":"dudak","az":"dodaq","es":"labio","en":"lip"}'::jsonb),
('teeth', '1F9B7', 'body', 'pre_a1_starters', false, '{"tr":"dişler","az":"dişlər","es":"dientes","en":"teeth"}'::jsonb),
('television', '1F4FA', 'home', 'pre_a1_starters', false, '{"tr":"televizyon","az":"televizor","es":"televisión","en":"television"}'::jsonb),
('radio', '1F4FB', 'home', 'pre_a1_starters', false, '{"tr":"radyo","az":"radio","es":"radio","en":"radio"}'::jsonb),
('phone', '260E', 'home', 'pre_a1_starters', false, '{"tr":"telefon","az":"telefon","es":"teléfono","en":"phone"}'::jsonb),
('camera', '1F4F7', 'home', 'pre_a1_starters', false, '{"tr":"kamera","az":"kamera","es":"cámara","en":"camera"}'::jsonb),
('box', '1F4E6', 'home', 'pre_a1_starters', false, '{"tr":"kutu","az":"qutu","es":"caja","en":"box"}'::jsonb),
('basket', '1F9FA', 'home', 'a2_flyers', false, '{"tr":"sepet","az":"səbət","es":"cesta","en":"basket"}'::jsonb),
('bottle', '1F37C', 'home', 'a1_movers', false, '{"tr":"şişe","az":"şüşə","es":"botella","en":"bottle"}'::jsonb),
('knife', '1F52A', 'home', 'a2_flyers', false, '{"tr":"bıçak","az":"bıçaq","es":"cuchillo","en":"knife"}'::jsonb),
('spoon', '1F944', 'home', 'a1_movers', false, '{"tr":"kaşık","az":"qaşıq","es":"cuchara","en":"spoon"}'::jsonb),
('honey', '1F36F', 'food', 'a2_flyers', false, '{"tr":"bal","az":"bal","es":"miel","en":"honey"}'::jsonb),
('jam', '1FAD9', 'food', 'a2_flyers', false, '{"tr":"reçel","az":"mürəbbə","es":"mermelada","en":"jam"}'::jsonb),
('butter', '1F9C8', 'food', 'a1_movers', false, '{"tr":"tereyağı","az":"kərə yağı","es":"mantequilla","en":"butter"}'::jsonb),
('yogurt', '1F963', 'food', 'a1_movers', false, '{"tr":"yoğurt","az":"qatıq","es":"yogur","en":"yogurt"}'::jsonb),
('pepper', '1F336', 'food', 'a2_flyers', false, '{"tr":"biber","az":"bibər","es":"pimienta","en":"pepper"}'::jsonb),
('tea', '1F375', 'food', 'a1_movers', false, '{"tr":"çay","az":"çay","es":"té","en":"tea"}'::jsonb),
('coffee', '2615', 'food', 'a1_movers', false, '{"tr":"kahve","az":"qəhvə","es":"café","en":"coffee"}'::jsonb),
('orange', '1F34A', 'food', 'pre_a1_starters', false, '{"tr":"portakal","az":"portağal","es":"naranja","en":"orange"}'::jsonb),
('peach', '1F351', 'food', 'a2_flyers', false, '{"tr":"şeftali","az":"şaftalı","es":"melocotón","en":"peach"}'::jsonb),
('strawberry', '1F353', 'food', 'a2_flyers', false, '{"tr":"çilek","az":"çiyələk","es":"fresa","en":"strawberry"}'::jsonb),
('cherry', '1F352', 'food', 'a2_flyers', false, '{"tr":"kiraz","az":"gilas","es":"cereza","en":"cherry"}'::jsonb),
('pool', '1F3CA', 'places', 'a1_movers', false, '{"tr":"havuz","az":"hovuz","es":"piscina","en":"pool"}'::jsonb),
('farm', '1F3DE', 'places', 'a1_movers', false, '{"tr":"çiftlik","az":"ferma","es":"granja","en":"farm"}'::jsonb),
('cafe', '2615', 'places', 'a1_movers', false, '{"tr":"kafe","az":"kafe","es":"cafetería","en":"cafe"}'::jsonb),
('restaurant', '1F37D', 'places', 'a2_flyers', false, '{"tr":"restoran","az":"restoran","es":"restaurante","en":"restaurant"}'::jsonb),
('poster', '1F5BC', 'school', 'a2_flyers', false, '{"tr":"poster","az":"poster","es":"póster","en":"poster"}'::jsonb),
('brush', '1F58C', 'school', 'a1_movers', false, '{"tr":"fırça","az":"fırça","es":"pincel","en":"brush"}'::jsonb),
('crayon', '1F58D', 'school', 'pre_a1_starters', false, '{"tr":"pastel boya","az":"pastel boya","es":"crayón","en":"crayon"}'::jsonb),
('belt', '1FA93', 'clothes', 'a2_flyers', false, '{"tr":"kemer","az":"kəmər","es":"cinturón","en":"belt"}'::jsonb),
('tie', '1F454', 'clothes', 'a2_flyers', false, '{"tr":"kravat","az":"qalstuk","es":"corbata","en":"tie"}'::jsonb),
('pyjamas', '1F455', 'clothes', 'a1_movers', false, '{"tr":"pijama","az":"pijama","es":"pijama","en":"pyjamas"}'::jsonb),
('slippers', '1FA70', 'clothes', 'a2_flyers', false, '{"tr":"terlik","az":"tərlik","es":"zapatillas","en":"slippers"}'::jsonb),
('puppy', '1F436', 'animals', 'pre_a1_starters', false, '{"tr":"köpek yavrusu","az":"küçük","es":"cachorro","en":"puppy"}'::jsonb),
('kitten', '1F431', 'animals', 'pre_a1_starters', false, '{"tr":"kedi yavrusu","az":"pişik balası","es":"gatito","en":"kitten"}'::jsonb),
('pet', '1F43E', 'animals', 'pre_a1_starters', false, '{"tr":"evcil hayvan","az":"ev heyvanı","es":"mascota","en":"pet"}'::jsonb),
('fox', '1F98A', 'animals', 'a2_flyers', false, '{"tr":"tilki","az":"tülkü","es":"zorro","en":"fox"}'::jsonb),
('wolf', '1F43A', 'animals', 'a2_flyers', false, '{"tr":"kurt","az":"qurd","es":"lobo","en":"wolf"}'::jsonb),
('deer', '1F98C', 'animals', 'a2_flyers', false, '{"tr":"geyik","az":"maral","es":"ciervo","en":"deer"}'::jsonb),
('snail', '1F40C', 'animals', 'a1_movers', false, '{"tr":"salyangoz","az":"ilbiz","es":"caracol","en":"snail"}'::jsonb),
('worm', '1F41B', 'animals', 'a2_flyers', false, '{"tr":"solucan","az":"soxulcan","es":"gusano","en":"worm"}'::jsonb),
('bee', '1F41D', 'animals', 'a1_movers', false, '{"tr":"arı","az":"arı","es":"abeja","en":"bee"}'::jsonb),
('ant', '1F41C', 'animals', 'a1_movers', false, '{"tr":"karınca","az":"qarışqa","es":"hormiga","en":"ant"}'::jsonb),
('easy', '1F44C', 'adjectives', 'a1_movers', false, '{"tr":"kolay","az":"asan","es":"fácil","en":"easy"}'::jsonb),
('difficult', '1F92F', 'adjectives', 'a2_flyers', false, '{"tr":"zor","az":"çətin","es":"difícil","en":"difficult"}'::jsonb),
('right', '2714', 'adjectives', 'pre_a1_starters', false, '{"tr":"doğru","az":"doğru","es":"correcto","en":"right"}'::jsonb),
('wrong', '274C', 'adjectives', 'pre_a1_starters', false, '{"tr":"yanlış","az":"səhv","es":"incorrecto","en":"wrong"}'::jsonb),
('strong', '1F4AA', 'adjectives', 'a1_movers', false, '{"tr":"güçlü","az":"güclü","es":"fuerte","en":"strong"}'::jsonb),
('weak', '1F912', 'adjectives', 'a1_movers', false, '{"tr":"zayıf","az":"zəif","es":"débil","en":"weak"}'::jsonb),
('fat', '1F974', 'adjectives', 'a1_movers', false, '{"tr":"şişman","az":"kök","es":"gordo","en":"fat"}'::jsonb),
('thin', '1F9CD', 'adjectives', 'a1_movers', false, '{"tr":"ince","az":"incə","es":"delgado","en":"thin"}'::jsonb),
('round', '26AA', 'adjectives', 'a2_flyers', false, '{"tr":"yuvarlak","az":"yumru","es":"redondo","en":"round"}'::jsonb),
('square', '2B1C', 'adjectives', 'a2_flyers', false, '{"tr":"kare","az":"kvadrat","es":"cuadrado","en":"square"}'::jsonb),
('buy', '1F6D2', 'actions', 'a1_movers', false, '{"tr":"satın almak","az":"almaq","es":"comprar","en":"buy"}'::jsonb),
('sell', '1F4B0', 'actions', 'a2_flyers', false, '{"tr":"satmak","az":"satmaq","es":"vender","en":"sell"}'::jsonb),
('pay', '1F4B3', 'actions', 'a2_flyers', false, '{"tr":"ödemek","az":"ödəmək","es":"pagar","en":"pay"}'::jsonb),
('hold', '1F91A', 'actions', 'a2_flyers', false, '{"tr":"tutmak","az":"tutmaq","es":"sostener","en":"hold"}'::jsonb),
('bring', '1F4E6', 'actions', 'a1_movers', false, '{"tr":"getirmek","az":"gətirmək","es":"traer","en":"bring"}'::jsonb),
('carry', '1F392', 'actions', 'a1_movers', false, '{"tr":"taşımak","az":"daşımaq","es":"llevar","en":"carry"}'::jsonb),
('find', '1F50D', 'actions', 'a1_movers', false, '{"tr":"bulmak","az":"tapmaq","es":"encontrar","en":"find"}'::jsonb),
('lose', '1F937', 'actions', 'a1_movers', false, '{"tr":"kaybetmek","az":"itirmək","es":"perder","en":"lose"}'::jsonb),
('hide', '1F648', 'actions', 'a1_movers', false, '{"tr":"saklanmak","az":"gizlənmək","es":"esconder","en":"hide"}'::jsonb),
('show', '1F441', 'actions', 'a1_movers', false, '{"tr":"göstermek","az":"göstərmək","es":"mostrar","en":"show"}'::jsonb),
('color', '1F3A8', 'actions', 'pre_a1_starters', false, '{"tr":"boyamak","az":"rəngləmək","es":"colorear","en":"color"}'::jsonb),
('cut', '2702', 'actions', 'a2_flyers', false, '{"tr":"kesmek","az":"kəsmək","es":"cortar","en":"cut"}'::jsonb),
('spring', '1F337', 'time', 'a1_movers', false, '{"tr":"ilkbahar","az":"yaz","es":"primavera","en":"spring"}'::jsonb),
('summer', '2600', 'time', 'a1_movers', false, '{"tr":"yaz","az":"yay","es":"verano","en":"summer"}'::jsonb),
('autumn', '1F342', 'time', 'a1_movers', false, '{"tr":"sonbahar","az":"payız","es":"otoño","en":"autumn"}'::jsonb),
('winter', '2744', 'time', 'a1_movers', false, '{"tr":"kış","az":"qış","es":"invierno","en":"winter"}'::jsonb),
('sunny', '2600', 'weather', 'a1_movers', false, '{"tr":"güneşli","az":"günəşli","es":"soleado","en":"sunny"}'::jsonb),
('rainy', '1F327', 'weather', 'a1_movers', false, '{"tr":"yağmurlu","az":"yağışlı","es":"lluvioso","en":"rainy"}'::jsonb),
('snowy', '1F328', 'weather', 'a1_movers', false, '{"tr":"karlı","az":"qarlı","es":"nevado","en":"snowy"}'::jsonb),
('cloudy', '2601', 'weather', 'a1_movers', false, '{"tr":"bulutlu","az":"buludlu","es":"nublado","en":"cloudy"}'::jsonb),
('windy', '1F32C', 'weather', 'a1_movers', false, '{"tr":"rüzgarlı","az":"küləkli","es":"ventoso","en":"windy"}'::jsonb),
('truthful', '1F90D', 'values', 'a2_flyers', true, '{"tr":"doğrucu","az":"doğrucul","es":"veraz","en":"truthful"}'::jsonb),
('obedient', '1F442', 'values', 'a2_flyers', true, '{"tr":"itaatkar","az":"itaətkar","es":"obediente","en":"obedient"}'::jsonb),
('independent', '1F9B8', 'values', 'a2_flyers', true, '{"tr":"bağımsız","az":"müstəqil","es":"independiente","en":"independent"}'::jsonb),
('curious', '1F9D0', 'values', 'a2_flyers', true, '{"tr":"meraklı","az":"maraqlı","es":"curioso","en":"curious"}'::jsonb),
('caring', '1F9E1', 'values', 'a2_flyers', true, '{"tr":"şefkatli","az":"qayğıkeş","es":"cariñoso","en":"caring"}'::jsonb),
('toy', '1F380', 'toys', 'pre_a1_starters', false, '{"tr":"oyuncak","az":"oyuncaq","es":"juguete","en":"toy"}'::jsonb),
('train set', '1F682', 'toys', 'a1_movers', false, '{"tr":"oyuncak tren","az":"oyuncaq qatar","es":"tren de juguete","en":"train set"}'::jsonb),
('drum', '1F941', 'toys', 'a1_movers', false, '{"tr":"davul","az":"təbil","es":"tambor","en":"drum"}'::jsonb),
('music', '1F3B5', 'school', 'pre_a1_starters', false, '{"tr":"müzik","az":"musiqi","es":"música","en":"music"}'::jsonb),
('song', '1F3B6', 'school', 'pre_a1_starters', false, '{"tr":"şarkı","az":"mahnı","es":"canción","en":"song"}'::jsonb),
('story', '1F4D6', 'school', 'pre_a1_starters', false, '{"tr":"hikaye","az":"hekayə","es":"historia","en":"story"}'::jsonb),
('movie', '1F3AC', 'school', 'a1_movers', false, '{"tr":"film","az":"film","es":"película","en":"movie"}'::jsonb),
('video', '1F4F9', 'school', 'a1_movers', false, '{"tr":"video","az":"video","es":"video","en":"video"}'::jsonb);
